[project]
name = "qql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Srimon", email = "srimon12mckv@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "connectrpc>=0.10.1",
    "httpx>=0.28.1",
    "protobuf>=7.35.1",
]

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"
