//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

func main() {
	keywords := map[string]string{
		"GEO_BBOX":     "TokenKindGeoBbox",
		"GEO_RADIUS":   "TokenKindGeoRadius",
		"VALUES_COUNT": "TokenKindValuesCount",
		"HAS_VECTOR":   "TokenKindHasVector",
		"BOOST":        "TokenKindBoost",
		"DEFAULTS":     "TokenKindDefaults",
		"CASE":         "TokenKindCase",
		"WHEN":         "TokenKindWhen",
		"THEN":         "TokenKindThen",
		"ELSE":         "TokenKindElse",
		"END":          "TokenKindEnd",
		"INSERT":       "TokenKindInsert",
		"INTO":         "TokenKindInto",
		"COLLECTION":   "TokenKindCollection",
		"VALUES":       "TokenKindValues",
		"USING":        "TokenKindUsing",
		"MODEL":        "TokenKindModel",
		"HYBRID":       "TokenKindHybrid",
		"DENSE":        "TokenKindDense",
		"SPARSE":       "TokenKindSparse",
		"RERANK":       "TokenKindRerank",
		"EXACT":        "TokenKindExact",
		"WITH":         "TokenKindWith",
		"AS":           "TokenKindAs",
		"ACORN":        "TokenKindAcorn",
		"QUANTIZE":     "TokenKindQuantize",
		"SCALAR":       "TokenKindScalar",
		"BINARY":       "TokenKindBinary",
		"PRODUCT":      "TokenKindProduct",
		"TURBO":        "TokenKindTurbo",
		"BITS":         "TokenKindBits",
		"QUANTILE":     "TokenKindQuantile",
		"ALWAYS":       "TokenKindAlways",
		"RAM":          "TokenKindRam",
		"HNSW":         "TokenKindHnsw",
		"VECTORS":      "TokenKindVectors",
		"OPTIMIZERS":   "TokenKindOptimizers",
		"PARAMS":       "TokenKindParams",
		"DISABLED":     "TokenKindDisabled",
		"CREATE":       "TokenKindCreate",
		"ALTER":        "TokenKindAlter",
		"DROP":         "TokenKindDrop",
		"SHOW":         "TokenKindShow",
		"COLLECTIONS":  "TokenKindCollections",
		"SELECT":       "TokenKindSelect",
		"SCROLL":       "TokenKindScroll",
		"AFTER":        "TokenKindAfter",
		"RECOMMEND":    "TokenKindRecommend",
		"QUERY":        "TokenKindQuery",
		"NEAREST":      "TokenKindNearest",
		"CONTEXT":      "TokenKindContext",
		"DISCOVER":     "TokenKindDiscover",
		"PAIRS":        "TokenKindPairs",
		"TARGET":       "TokenKindTarget",
		"ORDER":        "TokenKindOrder",
		"ASC":          "TokenKindAsc",
		"DESC":         "TokenKindDesc",
		"LIMIT":        "TokenKindLimit",
		"GROUP":        "TokenKindGroup",
		"BY":           "TokenKindBy",
		"GROUP_SIZE":   "TokenKindGroupSize",
		"STRATEGY":     "TokenKindStrategy",
		"DELETE":       "TokenKindDelete",
		"UPDATE":       "TokenKindUpdate",
		"SET":          "TokenKindSet",
		"VECTOR":       "TokenKindVector",
		"PAYLOAD":      "TokenKindPayload",
		"FROM":         "TokenKindFrom",
		"WHERE":        "TokenKindWhere",
		"ID":           "TokenKindId",
		"INDEX":        "TokenKindIndex",
		"ON":           "TokenKindOn",
		"FOR":          "TokenKindFor",
		"TYPE":         "TokenKindType",
		"AND":          "TokenKindAnd",
		"OR":           "TokenKindOr",
		"NOT":          "TokenKindNot",
		"IN":           "TokenKindIn",
		"BETWEEN":      "TokenKindBetween",
		"IS":           "TokenKindIs",
		"NULL":         "TokenKindNull",
		"EMPTY":        "TokenKindEmpty",
		"MATCH":        "TokenKindMatch",
		"ANY":          "TokenKindAny",
		"PHRASE":       "TokenKindPhrase",
		"OFFSET":       "TokenKindOffset",
		"SCORE":        "TokenKindScore",
		"THRESHOLD":    "TokenKindThreshold",
		"LOOKUP":       "TokenKindLookup",
		"COSINE":       "TokenKindCosine",
		"DOT":          "TokenKindDot",
		"EUCLID":       "TokenKindEuclid",
		"MANHATTAN":    "TokenKindManhattan",
		"PREFETCH":     "TokenKindPrefetch",
		"FUSION":       "TokenKindFusion",
		"SAMPLE":       "TokenKindSample",
		"RELEVANCE":    "TokenKindRelevance",
		"FEEDBACK":     "TokenKindFeedback",
	}

	byLength := make(map[int][]string)
	for k := range keywords {
		byLength[len(k)] = append(byLength[len(k)], k)
	}

	var lengths []int
	for l := range byLength {
		lengths = append(lengths, l)
	}
	sort.Ints(lengths)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by gen.go; DO NOT EDIT.\n\n")
	buf.WriteString("package lexer\n\n")
	buf.WriteString("func lookupKeywordFast(s string) (TokenKind, bool) {\n")
	buf.WriteString("\tswitch len(s) {\n")

	for _, l := range lengths {
		buf.WriteString(fmt.Sprintf("\tcase %d:\n", l))
		words := byLength[l]
		sort.Strings(words)
		for _, w := range words {
			buf.WriteString("\t\tif ")
			var conds []string
			for i := 0; i < l; i++ {
				c := w[i]
				lower := c + 32
				if c == '_' {
					conds = append(conds, fmt.Sprintf("s[%d] == '%c'", i, c))
				} else {
					conds = append(conds, fmt.Sprintf("(s[%d] == '%c' || s[%d] == '%c')", i, c, i, lower))
				}
			}
			buf.WriteString(strings.Join(conds, " && "))
			buf.WriteString(fmt.Sprintf(" {\n\t\t\treturn %s, true\n\t\t}\n", keywords[w]))
		}
	}
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn 0, false\n")
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}

	if err := os.WriteFile("lookup_fast.go", formatted, 0644); err != nil {
		panic(err)
	}
}
