//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"sort"
	"strings"
)

func main() {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, "lexer.go", nil, 0)
	if err != nil {
		log.Fatal(err)
	}

	var keywordsMap map[string]string

	ast.Inspect(node, func(n ast.Node) bool {
		switch x := n.(type) {
		case *ast.ValueSpec:
			if len(x.Names) > 0 && x.Names[0].Name == "keywords" {
				if cl, ok := x.Values[0].(*ast.CompositeLit); ok {
					keywordsMap = make(map[string]string)
					for _, elt := range cl.Elts {
						kv := elt.(*ast.KeyValueExpr)
						key := kv.Key.(*ast.BasicLit).Value
						key = strings.Trim(key, `"`)
						val := kv.Value.(*ast.Ident).Name
						keywordsMap[key] = val
					}
				}
				return false
			}
		}
		return true
	})

	if keywordsMap == nil {
		log.Fatal("keywords map not found")
	}

	lengths := make(map[int][]string)
	for kw := range keywordsMap {
		lengths[len(kw)] = append(lengths[len(kw)], kw)
	}

	var sortedLengths []int
	for l := range lengths {
		sortedLengths = append(sortedLengths, l)
	}
	sort.Ints(sortedLengths)

	var buf bytes.Buffer
	buf.WriteString(`// Code generated by go generate; DO NOT EDIT.

package lexer

func lookupKeywordFast(s string) (TokenKind, bool) {
	switch len(s) {
`)

	for _, l := range sortedLengths {
		kws := lengths[l]
		sort.Strings(kws)

		buf.WriteString(fmt.Sprintf("\tcase %d:\n", l))
		for _, kw := range kws {
			buf.WriteString("\t\tif ")
			for i := 0; i < len(kw); i++ {
				if i > 0 {
					buf.WriteString(" && ")
				}
				c := kw[i]
				lowerC := c
				if c >= 'A' && c <= 'Z' {
					lowerC += 32
				}

				if c == lowerC {
					buf.WriteString(fmt.Sprintf("(s[%d] == '%c')", i, c))
				} else {
					buf.WriteString(fmt.Sprintf("(s[%d] == '%c' || s[%d] == '%c')", i, c, i, lowerC))
				}
			}
			buf.WriteString(fmt.Sprintf(" {\n\t\t\treturn %s, true\n\t\t}\n", keywordsMap[kw]))
		}
	}

	buf.WriteString(`	}
	return 0, false
}
`)

	err = os.WriteFile("keyword_lookup.go", buf.Bytes(), 0644)
	if err != nil {
		log.Fatal(err)
	}
}
