//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

// keywords should match lexer.go
var keywords = map[string]string{
	"GEO_BBOX":     "TokenKindGeoBbox",
	"GEO_RADIUS":   "TokenKindGeoRadius",
	"VALUES_COUNT": "TokenKindValuesCount",
	"HAS_VECTOR":   "TokenKindHasVector",
	"BOOST":        "TokenKindBoost",
	"DEFAULTS":     "TokenKindDefaults",
	"CASE":         "TokenKindCase",
	"WHEN":         "TokenKindWhen",
	"THEN":         "TokenKindThen",
	"ELSE":         "TokenKindElse",
	"END":          "TokenKindEnd",
	"INSERT":       "TokenKindInsert",
	"INTO":         "TokenKindInto",
	"COLLECTION":   "TokenKindCollection",
	"VALUES":       "TokenKindValues",
	"USING":        "TokenKindUsing",
	"MODEL":        "TokenKindModel",
	"HYBRID":       "TokenKindHybrid",
	"DENSE":        "TokenKindDense",
	"SPARSE":       "TokenKindSparse",
	"RERANK":       "TokenKindRerank",
	"EXACT":        "TokenKindExact",
	"WITH":         "TokenKindWith",
	"AS":           "TokenKindAs",
	"ACORN":        "TokenKindAcorn",
	"QUANTIZE":     "TokenKindQuantize",
	"SCALAR":       "TokenKindScalar",
	"BINARY":       "TokenKindBinary",
	"PRODUCT":      "TokenKindProduct",
	"TURBO":        "TokenKindTurbo",
	"BITS":         "TokenKindBits",
	"QUANTILE":     "TokenKindQuantile",
	"ALWAYS":       "TokenKindAlways",
	"RAM":          "TokenKindRam",
	"HNSW":         "TokenKindHnsw",
	"VECTORS":      "TokenKindVectors",
	"OPTIMIZERS":   "TokenKindOptimizers",
	"PARAMS":       "TokenKindParams",
	"DISABLED":     "TokenKindDisabled",
	"CREATE":       "TokenKindCreate",
	"ALTER":        "TokenKindAlter",
	"DROP":         "TokenKindDrop",
	"SHOW":         "TokenKindShow",
	"COLLECTIONS":  "TokenKindCollections",
	"SELECT":       "TokenKindSelect",
	"SCROLL":       "TokenKindScroll",
	"AFTER":        "TokenKindAfter",
	"RECOMMEND":    "TokenKindRecommend",
	"QUERY":        "TokenKindQuery",
	"NEAREST":      "TokenKindNearest",
	"CONTEXT":      "TokenKindContext",
	"DISCOVER":     "TokenKindDiscover",
	"PAIRS":        "TokenKindPairs",
	"TARGET":       "TokenKindTarget",
	"ORDER":        "TokenKindOrder",
	"ASC":          "TokenKindAsc",
	"DESC":         "TokenKindDesc",
	"LIMIT":        "TokenKindLimit",
	"GROUP":        "TokenKindGroup",
	"BY":           "TokenKindBy",
	"GROUP_SIZE":   "TokenKindGroupSize",
	"STRATEGY":     "TokenKindStrategy",
	"DELETE":       "TokenKindDelete",
	"UPDATE":       "TokenKindUpdate",
	"SET":          "TokenKindSet",
	"VECTOR":       "TokenKindVector",
	"PAYLOAD":      "TokenKindPayload",
	"FROM":         "TokenKindFrom",
	"WHERE":        "TokenKindWhere",
	"ID":           "TokenKindId",
	"INDEX":        "TokenKindIndex",
	"ON":           "TokenKindOn",
	"FOR":          "TokenKindFor",
	"TYPE":         "TokenKindType",
	"AND":          "TokenKindAnd",
	"OR":           "TokenKindOr",
	"NOT":          "TokenKindNot",
	"IN":           "TokenKindIn",
	"BETWEEN":      "TokenKindBetween",
	"IS":           "TokenKindIs",
	"NULL":         "TokenKindNull",
	"EMPTY":        "TokenKindEmpty",
	"MATCH":        "TokenKindMatch",
	"ANY":          "TokenKindAny",
	"PHRASE":       "TokenKindPhrase",
	"OFFSET":       "TokenKindOffset",
	"SCORE":        "TokenKindScore",
	"THRESHOLD":    "TokenKindThreshold",
	"LOOKUP":       "TokenKindLookup",
	"COSINE":       "TokenKindCosine",
	"DOT":          "TokenKindDot",
	"EUCLID":       "TokenKindEuclid",
	"MANHATTAN":    "TokenKindManhattan",
	"PREFETCH":     "TokenKindPrefetch",
	"FUSION":       "TokenKindFusion",
	"SAMPLE":       "TokenKindSample",
	"RELEVANCE":    "TokenKindRelevance",
	"FEEDBACK":     "TokenKindFeedback",
}

func main() {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by gen_keywords.go; DO NOT EDIT.\n\n")
	buf.WriteString("package lexer\n\n")

	buf.WriteString("// lookupKeywordFast is an optimized keyword lookup function generated to prevent memory allocations.\n")
	buf.WriteString("func lookupKeywordFast(s string) (TokenKind, bool) {\n")
	buf.WriteString("\tswitch len(s) {\n")

	// Group by length
	byLength := make(map[int][]string)
	var lengths []int
	for k := range keywords {
		l := len(k)
		if _, ok := byLength[l]; !ok {
			lengths = append(lengths, l)
		}
		byLength[l] = append(byLength[l], k)
	}
	sort.Ints(lengths)

	for _, l := range lengths {
		words := byLength[l]
		sort.Strings(words)

		buf.WriteString(fmt.Sprintf("\tcase %d:\n", l))
		buf.WriteString("\t\tswitch {\n")

		for _, w := range words {
			buf.WriteString("\t\tcase ")
			var conditions []string
			for i := 0; i < len(w); i++ {
				c := w[i]
				cLower := c + 32
				if c == '_' {
					conditions = append(conditions, fmt.Sprintf("s[%d] == '%c'", i, c))
				} else {
					conditions = append(conditions, fmt.Sprintf("(s[%d] == '%c' || s[%d] == '%c')", i, c, i, cLower))
				}
			}
			buf.WriteString(strings.Join(conditions, " && "))
			buf.WriteString(fmt.Sprintf(":\n\t\t\treturn %s, true\n", keywords[w]))
		}
		buf.WriteString("\t\t}\n")
	}

	buf.WriteString("\t}\n")
	buf.WriteString("\treturn 0, false\n")
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Printf("Error formatting source: %v\n", err)
		os.Exit(1)
	}

	err = os.WriteFile("keywords_fast.go", formatted, 0644)
	if err != nil {
		fmt.Printf("Error writing file: %v\n", err)
		os.Exit(1)
	}
}
