//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"sort"
)

// keywords must be kept in sync with lexer.go
var keywords = map[string]string{
	"GEO_BBOX":     "TokenKindGeoBbox",
	"GEO_RADIUS":   "TokenKindGeoRadius",
	"VALUES_COUNT": "TokenKindValuesCount",
	"HAS_VECTOR":   "TokenKindHasVector",
	"BOOST":        "TokenKindBoost",
	"DEFAULTS":     "TokenKindDefaults",
	"CASE":         "TokenKindCase",
	"WHEN":         "TokenKindWhen",
	"THEN":         "TokenKindThen",
	"ELSE":         "TokenKindElse",
	"END":          "TokenKindEnd",
	"INSERT":       "TokenKindInsert",
	"INTO":         "TokenKindInto",
	"COLLECTION":   "TokenKindCollection",
	"VALUES":       "TokenKindValues",
	"USING":        "TokenKindUsing",
	"MODEL":        "TokenKindModel",
	"HYBRID":       "TokenKindHybrid",
	"DENSE":        "TokenKindDense",
	"SPARSE":       "TokenKindSparse",
	"RERANK":       "TokenKindRerank",
	"EXACT":        "TokenKindExact",
	"WITH":         "TokenKindWith",
	"AS":           "TokenKindAs",
	"ACORN":        "TokenKindAcorn",
	"QUANTIZE":     "TokenKindQuantize",
	"SCALAR":       "TokenKindScalar",
	"BINARY":       "TokenKindBinary",
	"PRODUCT":      "TokenKindProduct",
	"TURBO":        "TokenKindTurbo",
	"BITS":         "TokenKindBits",
	"QUANTILE":     "TokenKindQuantile",
	"ALWAYS":       "TokenKindAlways",
	"RAM":          "TokenKindRam",
	"HNSW":         "TokenKindHnsw",
	"VECTORS":      "TokenKindVectors",
	"OPTIMIZERS":   "TokenKindOptimizers",
	"PARAMS":       "TokenKindParams",
	"DISABLED":     "TokenKindDisabled",
	"CREATE":       "TokenKindCreate",
	"ALTER":        "TokenKindAlter",
	"DROP":         "TokenKindDrop",
	"SHOW":         "TokenKindShow",
	"COLLECTIONS":  "TokenKindCollections",
	"SELECT":       "TokenKindSelect",
	"SCROLL":       "TokenKindScroll",
	"AFTER":        "TokenKindAfter",
	"RECOMMEND":    "TokenKindRecommend",
	"QUERY":        "TokenKindQuery",
	"NEAREST":      "TokenKindNearest",
	"CONTEXT":      "TokenKindContext",
	"DISCOVER":     "TokenKindDiscover",
	"PAIRS":        "TokenKindPairs",
	"TARGET":       "TokenKindTarget",
	"ORDER":        "TokenKindOrder",
	"ASC":          "TokenKindAsc",
	"DESC":         "TokenKindDesc",
	"LIMIT":        "TokenKindLimit",
	"GROUP":        "TokenKindGroup",
	"BY":           "TokenKindBy",
	"GROUP_SIZE":   "TokenKindGroupSize",
	"STRATEGY":     "TokenKindStrategy",
	"DELETE":       "TokenKindDelete",
	"UPDATE":       "TokenKindUpdate",
	"SET":          "TokenKindSet",
	"VECTOR":       "TokenKindVector",
	"PAYLOAD":      "TokenKindPayload",
	"FROM":         "TokenKindFrom",
	"WHERE":        "TokenKindWhere",
	"ID":           "TokenKindId",
	"INDEX":        "TokenKindIndex",
	"ON":           "TokenKindOn",
	"FOR":          "TokenKindFor",
	"TYPE":         "TokenKindType",
	"AND":          "TokenKindAnd",
	"OR":           "TokenKindOr",
	"NOT":          "TokenKindNot",
	"IN":           "TokenKindIn",
	"BETWEEN":      "TokenKindBetween",
	"IS":           "TokenKindIs",
	"NULL":         "TokenKindNull",
	"EMPTY":        "TokenKindEmpty",
	"MATCH":        "TokenKindMatch",
	"ANY":          "TokenKindAny",
	"PHRASE":       "TokenKindPhrase",
	"OFFSET":       "TokenKindOffset",
	"SCORE":        "TokenKindScore",
	"THRESHOLD":    "TokenKindThreshold",
	"LOOKUP":       "TokenKindLookup",
	"COSINE":       "TokenKindCosine",
	"DOT":          "TokenKindDot",
	"EUCLID":       "TokenKindEuclid",
	"MANHATTAN":    "TokenKindManhattan",
	"PREFETCH":     "TokenKindPrefetch",
	"FUSION":       "TokenKindFusion",
	"SAMPLE":       "TokenKindSample",
	"RELEVANCE":    "TokenKindRelevance",
	"FEEDBACK":     "TokenKindFeedback",
}

func main() {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by gen_keywords.go; DO NOT EDIT.\n\n")
	buf.WriteString("package lexer\n\n")
	buf.WriteString("// lookupKeywordFast is an optimized keyword lookup function.\n")
	buf.WriteString("func lookupKeywordFast(s string) (TokenKind, bool) {\n")
	buf.WriteString("\tswitch len(s) {\n")

	// Group keywords by length
	byLen := make(map[int][]string)
	for kw := range keywords {
		byLen[len(kw)] = append(byLen[len(kw)], kw)
	}

	var lengths []int
	for l := range byLen {
		lengths = append(lengths, l)
	}
	sort.Ints(lengths)

	for _, l := range lengths {
		kws := byLen[l]
		sort.Strings(kws)
		buf.WriteString(fmt.Sprintf("\tcase %d:\n", l))

		for _, kw := range kws {
			kind := keywords[kw]

			// Build case-insensitive check manually for best performance
			buf.WriteString("\t\tif ")
			for i := 0; i < len(kw); i++ {
				if i > 0 {
					buf.WriteString(" && ")
				}
				if kw[i] >= 'A' && kw[i] <= 'Z' {
					buf.WriteString(fmt.Sprintf("(s[%d] == '%c' || s[%d] == '%c')", i, kw[i], i, kw[i]+32))
				} else {
					buf.WriteString(fmt.Sprintf("s[%d] == '%c'", i, kw[i]))
				}
			}
			buf.WriteString(" {\n")
			buf.WriteString(fmt.Sprintf("\t\t\treturn %s, true\n", kind))
			buf.WriteString("\t\t}\n")
		}
	}

	buf.WriteString("\t}\n")
	buf.WriteString("\treturn 0, false\n")
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error formatting generated code: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile("keywords_fast.go", formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing generated code: %v\n", err)
		os.Exit(1)
	}
}
