//go:build ignore

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

func main() {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "lexer.go", nil, 0)
	if err != nil {
		panic(err)
	}

	var keywordsMap *ast.CompositeLit
	for _, decl := range f.Decls {
		if gen, ok := decl.(*ast.GenDecl); ok && gen.Tok == token.VAR {
			for _, spec := range gen.Specs {
				if vs, ok := spec.(*ast.ValueSpec); ok {
					if len(vs.Names) == 1 && vs.Names[0].Name == "keywords" {
						if len(vs.Values) == 1 {
							if cl, ok := vs.Values[0].(*ast.CompositeLit); ok {
								keywordsMap = cl
							}
						}
					}
				}
			}
		}
	}

	if keywordsMap == nil {
		panic("keywords map not found")
	}

	type kw struct {
		name string
		kind string
	}
	var kws []kw

	for _, elt := range keywordsMap.Elts {
		if kv, ok := elt.(*ast.KeyValueExpr); ok {
			if k, ok := kv.Key.(*ast.BasicLit); ok && k.Kind == token.STRING {
				if v, ok := kv.Value.(*ast.Ident); ok {
					name := strings.Trim(k.Value, "\"")
					kws = append(kws, kw{name: name, kind: v.Name})
				}
			}
		}
	}

	sort.Slice(kws, func(i, j int) bool {
		return kws[i].name < kws[j].name
	})

	out, err := os.Create("lookup_gen.go")
	if err != nil {
		panic(err)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by gen_lexer.go; DO NOT EDIT.")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "package lexer")
	fmt.Fprintln(out, "")
	fmt.Fprintln(out, "func lookupKeywordFast(b []byte) (TokenKind, bool) {")
	fmt.Fprintln(out, "\tswitch string(b) {")
	for _, k := range kws {
		fmt.Fprintf(out, "\tcase %q:\n", k.name)
		fmt.Fprintf(out, "\t\treturn %s, true\n", k.kind)
	}
	fmt.Fprintln(out, "\tdefault:")
	fmt.Fprintln(out, "\t\treturn 0, false")
	fmt.Fprintln(out, "\t}")
	fmt.Fprintln(out, "}")
}
