//go:build ignore
// +build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strings"
)

func main() {
	// Read keywords from lexer.go (simplistic parsing)
	content, err := os.ReadFile("lexer.go")
	if err != nil {
		log.Fatal(err)
	}

	lines := strings.Split(string(content), "\n")
	var inMap bool
	var keywords []struct{ kw, kind string }

	for _, line := range lines {
		if strings.Contains(line, "var keywords = map[string]TokenKind{") {
			inMap = true
			continue
		}
		if inMap && strings.Contains(line, "}") {
			break
		}
		if inMap {
			parts := strings.SplitN(line, ":", 2)
			if len(parts) == 2 {
				kw := strings.TrimSpace(parts[0])
				kw = strings.Trim(kw, `"`)
				kind := strings.TrimSpace(parts[1])
				kind = strings.TrimSuffix(kind, ",")
				keywords = append(keywords, struct{ kw, kind string }{kw, kind})
			}
		}
	}

	sort.Slice(keywords, func(i, j int) bool {
		return keywords[i].kw < keywords[j].kw
	})

	var buf bytes.Buffer
	buf.WriteString(`// Code generated by gen_lookup.go; DO NOT EDIT.
package lexer

func lookupKeywordFast(s string) (TokenKind, bool) {
	switch len(s) {
`)

	byLen := make(map[int][]struct{ kw, kind string })
	for _, k := range keywords {
		byLen[len(k.kw)] = append(byLen[len(k.kw)], k)
	}

	var lens []int
	for l := range byLen {
		lens = append(lens, l)
	}
	sort.Ints(lens)

	for _, l := range lens {
		buf.WriteString(fmt.Sprintf("\tcase %d:\n", l))
		for _, k := range byLen[l] {
			buf.WriteString(fmt.Sprintf("\t\tif equalsCaseInsensitive(s, %q) {\n", k.kw))
			buf.WriteString(fmt.Sprintf("\t\t\treturn %s, true\n", k.kind))
			buf.WriteString("\t\t}\n")
		}
	}

	buf.WriteString(`	}
	return 0, false
}

func equalsCaseInsensitive(s, upper string) bool {
	if len(s) != len(upper) {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c >= 'a' && c <= 'z' {
			c -= 32
		}
		if c != upper[i] {
			return false
		}
	}
	return true
}
`)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("format error: %v\n%s", err, buf.String())
	}

	if err := os.WriteFile("lookup_fast.go", formatted, 0644); err != nil {
		log.Fatal(err)
	}
}
