//go:build ignore

package main

import (
	"fmt"
	"os"
	"regexp"
	"sort"
)

func main() {
	b, err := os.ReadFile("lexer.go")
	if err != nil {
		panic(err)
	}
	re := regexp.MustCompile(`"([A-Z_]+)":\s*(TokenKind[A-Za-z]+)`)
	matches := re.FindAllStringSubmatch(string(b), -1)

	type kw struct {
		word string
		kind string
	}

	var kws []kw
	for _, m := range matches {
		kws = append(kws, kw{m[1], m[2]})
	}

	// Group by length
	byLen := make(map[int][]kw)
	for _, k := range kws {
		byLen[len(k.word)] = append(byLen[len(k.word)], k)
	}

	var lengths []int
	for l := range byLen {
		lengths = append(lengths, l)
	}
	sort.Ints(lengths)

	out := `// Code generated by generate.go. DO NOT EDIT.
package lexer

// lookupKeywordFast is a generated case-insensitive keyword lookup
func lookupKeywordFast(s string) (TokenKind, bool) {
	switch len(s) {
`
	for _, l := range lengths {
		out += fmt.Sprintf("\tcase %d:\n", l)
		for _, k := range byLen[l] {
			out += fmt.Sprintf("\t\t// %s\n", k.word)
			out += fmt.Sprintf("\t\tif ")
			for i := 0; i < l; i++ {
				if i > 0 {
					out += " && "
				}
				c := k.word[i]
				lower := c + 32
				if c == '_' {
					out += fmt.Sprintf("s[%d] == '_'", i)
				} else {
					out += fmt.Sprintf("(s[%d] == '%c' || s[%d] == '%c')", i, c, i, lower)
				}
			}
			out += fmt.Sprintf(" {\n\t\t\treturn %s, true\n\t\t}\n", k.kind)
		}
	}

	out += "\t}\n\treturn 0, false\n}\n"

	err = os.WriteFile("lookup_fast.go", []byte(out), 0644)
	if err != nil {
		panic(err)
	}
}
