//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"sort"
	"strings"
)

func main() {
	content, err := os.ReadFile("lexer.go")
	if err != nil {
		panic(err)
	}

	startIdx := bytes.Index(content, []byte("var keywords = map[string]TokenKind{"))
	endIdx := bytes.Index(content[startIdx:], []byte("}")) + startIdx

	mapLines := bytes.Split(content[startIdx:endIdx], []byte("\n"))

	byLength := make(map[int]map[string]string)
	for _, line := range mapLines[1:] {
		lineStr := strings.TrimSpace(string(line))
		if lineStr == "" || strings.HasPrefix(lineStr, "//") {
			continue
		}
		parts := strings.SplitN(lineStr, ":", 2)
		if len(parts) != 2 {
			continue
		}
		kwStr := strings.Trim(strings.TrimSpace(parts[0]), `"`)
		kindStr := strings.TrimSuffix(strings.TrimSpace(parts[1]), ",")

		l := len(kwStr)
		if byLength[l] == nil {
			byLength[l] = make(map[string]string)
		}
		byLength[l][kwStr] = kindStr
	}

	var buf bytes.Buffer
	buf.WriteString(`// Code generated by go generate; DO NOT EDIT.
package lexer

func lookupKeywordFast(s string) (TokenKind, bool) {
	if len(s) == 0 {
		return 0, false
	}
	switch len(s) {
`)

	var lengths []int
	for l := range byLength {
		lengths = append(lengths, l)
	}
	sort.Ints(lengths)

	for _, l := range lengths {
		buf.WriteString(fmt.Sprintf("\tcase %d:\n", l))
		buf.WriteString("\t\tswitch s[0] | 0x20 {\n")

		byFirstChar := make(map[byte]map[string]string)
		for kw, kind := range byLength[l] {
			fc := kw[0] | 0x20
			if byFirstChar[fc] == nil {
				byFirstChar[fc] = make(map[string]string)
			}
			byFirstChar[fc][kw] = kind
		}

		var chars []int
		for c := range byFirstChar {
			chars = append(chars, int(c))
		}
		sort.Ints(chars)

		for _, cInt := range chars {
			c := byte(cInt)
			buf.WriteString(fmt.Sprintf("\t\tcase '%c':\n", c))

			var sortedKws []string
			for kw := range byFirstChar[c] {
				sortedKws = append(sortedKws, kw)
			}
			sort.Strings(sortedKws)

			for _, kw := range sortedKws {
				kind := byFirstChar[c][kw]
				buf.WriteString("\t\t\tif ")
				for i := 1; i < len(kw); i++ {
					if i > 1 {
						buf.WriteString(" && ")
					}
					lc := kw[i] | 0x20
					if lc >= 'a' && lc <= 'z' {
						buf.WriteString(fmt.Sprintf("(s[%d] | 0x20) == '%c'", i, lc))
					} else {
						buf.WriteString(fmt.Sprintf("s[%d] == '%c'", i, kw[i]))
					}
				}
				if len(kw) == 1 {
					buf.WriteString("true")
				}
				buf.WriteString(" {\n")
				buf.WriteString(fmt.Sprintf("\t\t\t\treturn %s, true\n", kind))
				buf.WriteString("\t\t\t}\n")
			}
		}
		buf.WriteString("\t\t}\n")
	}

	buf.WriteString("\t}\n")
	buf.WriteString("\treturn 0, false\n}\n")

	err = os.WriteFile("keyword_lookup.go", buf.Bytes(), 0644)
	if err != nil {
		panic(err)
	}

	exec.Command("gofmt", "-w", "keyword_lookup.go").Run()
}
