//go:build ignore
// +build ignore

package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

var keywords = map[string]string{
	"GEO_BBOX":     "TokenKindGeoBbox",
	"GEO_RADIUS":   "TokenKindGeoRadius",
	"VALUES_COUNT": "TokenKindValuesCount",
	"HAS_VECTOR":   "TokenKindHasVector",
	"BOOST":        "TokenKindBoost",
	"DEFAULTS":     "TokenKindDefaults",
	"CASE":         "TokenKindCase",
	"WHEN":         "TokenKindWhen",
	"THEN":         "TokenKindThen",
	"ELSE":         "TokenKindElse",
	"END":          "TokenKindEnd",
	"INSERT":       "TokenKindInsert",
	"INTO":         "TokenKindInto",
	"COLLECTION":   "TokenKindCollection",
	"VALUES":       "TokenKindValues",
	"USING":        "TokenKindUsing",
	"MODEL":        "TokenKindModel",
	"HYBRID":       "TokenKindHybrid",
	"DENSE":        "TokenKindDense",
	"SPARSE":       "TokenKindSparse",
	"RERANK":       "TokenKindRerank",
	"EXACT":        "TokenKindExact",
	"WITH":         "TokenKindWith",
	"AS":           "TokenKindAs",
	"ACORN":        "TokenKindAcorn",
	"QUANTIZE":     "TokenKindQuantize",
	"SCALAR":       "TokenKindScalar",
	"BINARY":       "TokenKindBinary",
	"PRODUCT":      "TokenKindProduct",
	"TURBO":        "TokenKindTurbo",
	"BITS":         "TokenKindBits",
	"QUANTILE":     "TokenKindQuantile",
	"ALWAYS":       "TokenKindAlways",
	"RAM":          "TokenKindRam",
	"HNSW":         "TokenKindHnsw",
	"VECTORS":      "TokenKindVectors",
	"OPTIMIZERS":   "TokenKindOptimizers",
	"PARAMS":       "TokenKindParams",
	"DISABLED":     "TokenKindDisabled",
	"CREATE":       "TokenKindCreate",
	"ALTER":        "TokenKindAlter",
	"DROP":         "TokenKindDrop",
	"SHOW":         "TokenKindShow",
	"COLLECTIONS":  "TokenKindCollections",
	"SELECT":       "TokenKindSelect",
	"SCROLL":       "TokenKindScroll",
	"AFTER":        "TokenKindAfter",
	"RECOMMEND":    "TokenKindRecommend",
	"QUERY":        "TokenKindQuery",
	"NEAREST":      "TokenKindNearest",
	"CONTEXT":      "TokenKindContext",
	"DISCOVER":     "TokenKindDiscover",
	"PAIRS":        "TokenKindPairs",
	"TARGET":       "TokenKindTarget",
	"ORDER":        "TokenKindOrder",
	"ASC":          "TokenKindAsc",
	"DESC":         "TokenKindDesc",
	"LIMIT":        "TokenKindLimit",
	"GROUP":        "TokenKindGroup",
	"BY":           "TokenKindBy",
	"GROUP_SIZE":   "TokenKindGroupSize",
	"STRATEGY":     "TokenKindStrategy",
	"DELETE":       "TokenKindDelete",
	"UPDATE":       "TokenKindUpdate",
	"SET":          "TokenKindSet",
	"VECTOR":       "TokenKindVector",
	"PAYLOAD":      "TokenKindPayload",
	"FROM":         "TokenKindFrom",
	"WHERE":        "TokenKindWhere",
	"ID":           "TokenKindId",
	"INDEX":        "TokenKindIndex",
	"ON":           "TokenKindOn",
	"FOR":          "TokenKindFor",
	"TYPE":         "TokenKindType",
	"AND":          "TokenKindAnd",
	"OR":           "TokenKindOr",
	"NOT":          "TokenKindNot",
	"IN":           "TokenKindIn",
	"BETWEEN":      "TokenKindBetween",
	"IS":           "TokenKindIs",
	"NULL":         "TokenKindNull",
	"EMPTY":        "TokenKindEmpty",
	"MATCH":        "TokenKindMatch",
	"ANY":          "TokenKindAny",
	"PHRASE":       "TokenKindPhrase",
	"OFFSET":       "TokenKindOffset",
	"SCORE":        "TokenKindScore",
	"THRESHOLD":    "TokenKindThreshold",
	"LOOKUP":       "TokenKindLookup",
	"COSINE":       "TokenKindCosine",
	"DOT":          "TokenKindDot",
	"EUCLID":       "TokenKindEuclid",
	"MANHATTAN":    "TokenKindManhattan",
	"PREFETCH":     "TokenKindPrefetch",
	"FUSION":       "TokenKindFusion",
	"SAMPLE":       "TokenKindSample",
	"RELEVANCE":    "TokenKindRelevance",
	"FEEDBACK":     "TokenKindFeedback",
}

func main() {
	var sb strings.Builder
	sb.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	sb.WriteString("package lexer\n\n")

	sb.WriteString("func lookupKeywordFast(s string) (TokenKind, bool) {\n")
	sb.WriteString("\tswitch len(s) {\n")

	byLen := make(map[int][]string)
	for kw := range keywords {
		byLen[len(kw)] = append(byLen[len(kw)], kw)
	}

	var lens []int
	for l := range byLen {
		lens = append(lens, l)
	}
	sort.Ints(lens)

	for _, l := range lens {
		kws := byLen[l]
		sort.Strings(kws)

		sb.WriteString(fmt.Sprintf("\tcase %d:\n", l))
		for i, kw := range kws {
			if i > 0 {
				sb.WriteString("\t\t} else ")
			} else {
				sb.WriteString("\t\t")
			}

			conds := []string{}
			for j := 0; j < len(kw); j++ {
				c := kw[j]
				lower := c + 32
				if c >= 'A' && c <= 'Z' {
					conds = append(conds, fmt.Sprintf("(s[%d] == '%c' || s[%d] == '%c')", j, c, j, lower))
				} else {
					conds = append(conds, fmt.Sprintf("s[%d] == '%c'", j, c))
				}
			}
			sb.WriteString(fmt.Sprintf("if %s {\n", strings.Join(conds, " && ")))
			sb.WriteString(fmt.Sprintf("\t\t\treturn %s, true\n", keywords[kw]))
		}
		sb.WriteString("\t\t}\n")
	}

	sb.WriteString("\t}\n")
	sb.WriteString("\treturn 0, false\n")
	sb.WriteString("}\n")

	os.WriteFile("lookup_fast.go", []byte(sb.String()), 0644)
}
