// Code generated by go generate; DO NOT EDIT.

package lexer

func lookupKeywordFast(s string) (TokenKind, bool) {
	if len(s) == 0 {
		return 0, false
	}
	switch len(s) {
	case 2:
		switch s[0] | 0x20 {
		case 'a':
			if hasPrefixCaseInsensitive(s, "AS") {
				return TokenKindAs, true
			}
		case 'b':
			if hasPrefixCaseInsensitive(s, "BY") {
				return TokenKindBy, true
			}
		case 'i':
			if hasPrefixCaseInsensitive(s, "ID") {
				return TokenKindId, true
			}
			if hasPrefixCaseInsensitive(s, "IN") {
				return TokenKindIn, true
			}
			if hasPrefixCaseInsensitive(s, "IS") {
				return TokenKindIs, true
			}
		case 'o':
			if hasPrefixCaseInsensitive(s, "ON") {
				return TokenKindOn, true
			}
			if hasPrefixCaseInsensitive(s, "OR") {
				return TokenKindOr, true
			}
		}
	case 3:
		switch s[0] | 0x20 {
		case 'a':
			if hasPrefixCaseInsensitive(s, "AND") {
				return TokenKindAnd, true
			}
			if hasPrefixCaseInsensitive(s, "ANY") {
				return TokenKindAny, true
			}
			if hasPrefixCaseInsensitive(s, "ASC") {
				return TokenKindAsc, true
			}
		case 'd':
			if hasPrefixCaseInsensitive(s, "DOT") {
				return TokenKindDot, true
			}
		case 'e':
			if hasPrefixCaseInsensitive(s, "END") {
				return TokenKindEnd, true
			}
		case 'f':
			if hasPrefixCaseInsensitive(s, "FOR") {
				return TokenKindFor, true
			}
		case 'n':
			if hasPrefixCaseInsensitive(s, "NOT") {
				return TokenKindNot, true
			}
		case 'r':
			if hasPrefixCaseInsensitive(s, "RAM") {
				return TokenKindRam, true
			}
		case 's':
			if hasPrefixCaseInsensitive(s, "SET") {
				return TokenKindSet, true
			}
		}
	case 4:
		switch s[0] | 0x20 {
		case 'b':
			if hasPrefixCaseInsensitive(s, "BITS") {
				return TokenKindBits, true
			}
		case 'c':
			if hasPrefixCaseInsensitive(s, "CASE") {
				return TokenKindCase, true
			}
		case 'd':
			if hasPrefixCaseInsensitive(s, "DESC") {
				return TokenKindDesc, true
			}
			if hasPrefixCaseInsensitive(s, "DROP") {
				return TokenKindDrop, true
			}
		case 'e':
			if hasPrefixCaseInsensitive(s, "ELSE") {
				return TokenKindElse, true
			}
		case 'f':
			if hasPrefixCaseInsensitive(s, "FROM") {
				return TokenKindFrom, true
			}
		case 'h':
			if hasPrefixCaseInsensitive(s, "HNSW") {
				return TokenKindHnsw, true
			}
		case 'i':
			if hasPrefixCaseInsensitive(s, "INTO") {
				return TokenKindInto, true
			}
		case 'n':
			if hasPrefixCaseInsensitive(s, "NULL") {
				return TokenKindNull, true
			}
		case 's':
			if hasPrefixCaseInsensitive(s, "SHOW") {
				return TokenKindShow, true
			}
		case 't':
			if hasPrefixCaseInsensitive(s, "THEN") {
				return TokenKindThen, true
			}
			if hasPrefixCaseInsensitive(s, "TYPE") {
				return TokenKindType, true
			}
		case 'w':
			if hasPrefixCaseInsensitive(s, "WHEN") {
				return TokenKindWhen, true
			}
			if hasPrefixCaseInsensitive(s, "WITH") {
				return TokenKindWith, true
			}
		}
	case 5:
		switch s[0] | 0x20 {
		case 'a':
			if hasPrefixCaseInsensitive(s, "ACORN") {
				return TokenKindAcorn, true
			}
			if hasPrefixCaseInsensitive(s, "AFTER") {
				return TokenKindAfter, true
			}
			if hasPrefixCaseInsensitive(s, "ALTER") {
				return TokenKindAlter, true
			}
		case 'b':
			if hasPrefixCaseInsensitive(s, "BOOST") {
				return TokenKindBoost, true
			}
		case 'd':
			if hasPrefixCaseInsensitive(s, "DENSE") {
				return TokenKindDense, true
			}
		case 'e':
			if hasPrefixCaseInsensitive(s, "EMPTY") {
				return TokenKindEmpty, true
			}
			if hasPrefixCaseInsensitive(s, "EXACT") {
				return TokenKindExact, true
			}
		case 'g':
			if hasPrefixCaseInsensitive(s, "GROUP") {
				return TokenKindGroup, true
			}
		case 'i':
			if hasPrefixCaseInsensitive(s, "INDEX") {
				return TokenKindIndex, true
			}
		case 'l':
			if hasPrefixCaseInsensitive(s, "LIMIT") {
				return TokenKindLimit, true
			}
		case 'm':
			if hasPrefixCaseInsensitive(s, "MATCH") {
				return TokenKindMatch, true
			}
			if hasPrefixCaseInsensitive(s, "MODEL") {
				return TokenKindModel, true
			}
		case 'o':
			if hasPrefixCaseInsensitive(s, "ORDER") {
				return TokenKindOrder, true
			}
		case 'p':
			if hasPrefixCaseInsensitive(s, "PAIRS") {
				return TokenKindPairs, true
			}
		case 'q':
			if hasPrefixCaseInsensitive(s, "QUERY") {
				return TokenKindQuery, true
			}
		case 's':
			if hasPrefixCaseInsensitive(s, "SCORE") {
				return TokenKindScore, true
			}
		case 't':
			if hasPrefixCaseInsensitive(s, "TURBO") {
				return TokenKindTurbo, true
			}
		case 'u':
			if hasPrefixCaseInsensitive(s, "USING") {
				return TokenKindUsing, true
			}
		case 'w':
			if hasPrefixCaseInsensitive(s, "WHERE") {
				return TokenKindWhere, true
			}
		}
	case 6:
		switch s[0] | 0x20 {
		case 'a':
			if hasPrefixCaseInsensitive(s, "ALWAYS") {
				return TokenKindAlways, true
			}
		case 'b':
			if hasPrefixCaseInsensitive(s, "BINARY") {
				return TokenKindBinary, true
			}
		case 'c':
			if hasPrefixCaseInsensitive(s, "COSINE") {
				return TokenKindCosine, true
			}
			if hasPrefixCaseInsensitive(s, "CREATE") {
				return TokenKindCreate, true
			}
		case 'd':
			if hasPrefixCaseInsensitive(s, "DELETE") {
				return TokenKindDelete, true
			}
		case 'e':
			if hasPrefixCaseInsensitive(s, "EUCLID") {
				return TokenKindEuclid, true
			}
		case 'f':
			if hasPrefixCaseInsensitive(s, "FUSION") {
				return TokenKindFusion, true
			}
		case 'h':
			if hasPrefixCaseInsensitive(s, "HYBRID") {
				return TokenKindHybrid, true
			}
		case 'i':
			if hasPrefixCaseInsensitive(s, "INSERT") {
				return TokenKindInsert, true
			}
		case 'l':
			if hasPrefixCaseInsensitive(s, "LOOKUP") {
				return TokenKindLookup, true
			}
		case 'o':
			if hasPrefixCaseInsensitive(s, "OFFSET") {
				return TokenKindOffset, true
			}
		case 'p':
			if hasPrefixCaseInsensitive(s, "PARAMS") {
				return TokenKindParams, true
			}
			if hasPrefixCaseInsensitive(s, "PHRASE") {
				return TokenKindPhrase, true
			}
		case 'r':
			if hasPrefixCaseInsensitive(s, "RERANK") {
				return TokenKindRerank, true
			}
		case 's':
			if hasPrefixCaseInsensitive(s, "SAMPLE") {
				return TokenKindSample, true
			}
			if hasPrefixCaseInsensitive(s, "SCALAR") {
				return TokenKindScalar, true
			}
			if hasPrefixCaseInsensitive(s, "SCROLL") {
				return TokenKindScroll, true
			}
			if hasPrefixCaseInsensitive(s, "SELECT") {
				return TokenKindSelect, true
			}
			if hasPrefixCaseInsensitive(s, "SPARSE") {
				return TokenKindSparse, true
			}
		case 't':
			if hasPrefixCaseInsensitive(s, "TARGET") {
				return TokenKindTarget, true
			}
		case 'u':
			if hasPrefixCaseInsensitive(s, "UPDATE") {
				return TokenKindUpdate, true
			}
		case 'v':
			if hasPrefixCaseInsensitive(s, "VALUES") {
				return TokenKindValues, true
			}
			if hasPrefixCaseInsensitive(s, "VECTOR") {
				return TokenKindVector, true
			}
		}
	case 7:
		switch s[0] | 0x20 {
		case 'b':
			if hasPrefixCaseInsensitive(s, "BETWEEN") {
				return TokenKindBetween, true
			}
		case 'c':
			if hasPrefixCaseInsensitive(s, "CONTEXT") {
				return TokenKindContext, true
			}
		case 'n':
			if hasPrefixCaseInsensitive(s, "NEAREST") {
				return TokenKindNearest, true
			}
		case 'p':
			if hasPrefixCaseInsensitive(s, "PAYLOAD") {
				return TokenKindPayload, true
			}
			if hasPrefixCaseInsensitive(s, "PRODUCT") {
				return TokenKindProduct, true
			}
		case 'v':
			if hasPrefixCaseInsensitive(s, "VECTORS") {
				return TokenKindVectors, true
			}
		}
	case 8:
		switch s[0] | 0x20 {
		case 'd':
			if hasPrefixCaseInsensitive(s, "DEFAULTS") {
				return TokenKindDefaults, true
			}
			if hasPrefixCaseInsensitive(s, "DISABLED") {
				return TokenKindDisabled, true
			}
			if hasPrefixCaseInsensitive(s, "DISCOVER") {
				return TokenKindDiscover, true
			}
		case 'f':
			if hasPrefixCaseInsensitive(s, "FEEDBACK") {
				return TokenKindFeedback, true
			}
		case 'g':
			if hasPrefixCaseInsensitive(s, "GEO_BBOX") {
				return TokenKindGeoBbox, true
			}
		case 'p':
			if hasPrefixCaseInsensitive(s, "PREFETCH") {
				return TokenKindPrefetch, true
			}
		case 'q':
			if hasPrefixCaseInsensitive(s, "QUANTILE") {
				return TokenKindQuantile, true
			}
			if hasPrefixCaseInsensitive(s, "QUANTIZE") {
				return TokenKindQuantize, true
			}
		case 's':
			if hasPrefixCaseInsensitive(s, "STRATEGY") {
				return TokenKindStrategy, true
			}
		}
	case 9:
		switch s[0] | 0x20 {
		case 'm':
			if hasPrefixCaseInsensitive(s, "MANHATTAN") {
				return TokenKindManhattan, true
			}
		case 'r':
			if hasPrefixCaseInsensitive(s, "RECOMMEND") {
				return TokenKindRecommend, true
			}
			if hasPrefixCaseInsensitive(s, "RELEVANCE") {
				return TokenKindRelevance, true
			}
		case 't':
			if hasPrefixCaseInsensitive(s, "THRESHOLD") {
				return TokenKindThreshold, true
			}
		}
	case 10:
		switch s[0] | 0x20 {
		case 'c':
			if hasPrefixCaseInsensitive(s, "COLLECTION") {
				return TokenKindCollection, true
			}
		case 'g':
			if hasPrefixCaseInsensitive(s, "GEO_RADIUS") {
				return TokenKindGeoRadius, true
			}
			if hasPrefixCaseInsensitive(s, "GROUP_SIZE") {
				return TokenKindGroupSize, true
			}
		case 'h':
			if hasPrefixCaseInsensitive(s, "HAS_VECTOR") {
				return TokenKindHasVector, true
			}
		case 'o':
			if hasPrefixCaseInsensitive(s, "OPTIMIZERS") {
				return TokenKindOptimizers, true
			}
		}
	case 11:
		switch s[0] | 0x20 {
		case 'c':
			if hasPrefixCaseInsensitive(s, "COLLECTIONS") {
				return TokenKindCollections, true
			}
		}
	case 12:
		switch s[0] | 0x20 {
		case 'v':
			if hasPrefixCaseInsensitive(s, "VALUES_COUNT") {
				return TokenKindValuesCount, true
			}
		}
	}
	return 0, false
}
