// Code generated by go generate; DO NOT EDIT.
package lexer

func lookupKeywordFast(s string) (TokenKind, bool) {
	if len(s) == 0 {
		return 0, false
	}
	switch len(s) {
	case 2:
		switch s[0] | 0x20 {
		case 'a':
			if (s[1] | 0x20) == 's' {
				return TokenKindAs, true
			}
		case 'b':
			if (s[1] | 0x20) == 'y' {
				return TokenKindBy, true
			}
		case 'i':
			if (s[1] | 0x20) == 'd' {
				return TokenKindId, true
			}
			if (s[1] | 0x20) == 'n' {
				return TokenKindIn, true
			}
			if (s[1] | 0x20) == 's' {
				return TokenKindIs, true
			}
		case 'o':
			if (s[1] | 0x20) == 'n' {
				return TokenKindOn, true
			}
			if (s[1] | 0x20) == 'r' {
				return TokenKindOr, true
			}
		}
	case 3:
		switch s[0] | 0x20 {
		case 'a':
			if (s[1]|0x20) == 'n' && (s[2]|0x20) == 'd' {
				return TokenKindAnd, true
			}
			if (s[1]|0x20) == 'n' && (s[2]|0x20) == 'y' {
				return TokenKindAny, true
			}
			if (s[1]|0x20) == 's' && (s[2]|0x20) == 'c' {
				return TokenKindAsc, true
			}
		case 'd':
			if (s[1]|0x20) == 'o' && (s[2]|0x20) == 't' {
				return TokenKindDot, true
			}
		case 'e':
			if (s[1]|0x20) == 'n' && (s[2]|0x20) == 'd' {
				return TokenKindEnd, true
			}
		case 'f':
			if (s[1]|0x20) == 'o' && (s[2]|0x20) == 'r' {
				return TokenKindFor, true
			}
		case 'n':
			if (s[1]|0x20) == 'o' && (s[2]|0x20) == 't' {
				return TokenKindNot, true
			}
		case 'r':
			if (s[1]|0x20) == 'a' && (s[2]|0x20) == 'm' {
				return TokenKindRam, true
			}
		case 's':
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 't' {
				return TokenKindSet, true
			}
		}
	case 4:
		switch s[0] | 0x20 {
		case 'b':
			if (s[1]|0x20) == 'i' && (s[2]|0x20) == 't' && (s[3]|0x20) == 's' {
				return TokenKindBits, true
			}
		case 'c':
			if (s[1]|0x20) == 'a' && (s[2]|0x20) == 's' && (s[3]|0x20) == 'e' {
				return TokenKindCase, true
			}
		case 'd':
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 's' && (s[3]|0x20) == 'c' {
				return TokenKindDesc, true
			}
			if (s[1]|0x20) == 'r' && (s[2]|0x20) == 'o' && (s[3]|0x20) == 'p' {
				return TokenKindDrop, true
			}
		case 'e':
			if (s[1]|0x20) == 'l' && (s[2]|0x20) == 's' && (s[3]|0x20) == 'e' {
				return TokenKindElse, true
			}
		case 'f':
			if (s[1]|0x20) == 'r' && (s[2]|0x20) == 'o' && (s[3]|0x20) == 'm' {
				return TokenKindFrom, true
			}
		case 'h':
			if (s[1]|0x20) == 'n' && (s[2]|0x20) == 's' && (s[3]|0x20) == 'w' {
				return TokenKindHnsw, true
			}
		case 'i':
			if (s[1]|0x20) == 'n' && (s[2]|0x20) == 't' && (s[3]|0x20) == 'o' {
				return TokenKindInto, true
			}
		case 'n':
			if (s[1]|0x20) == 'u' && (s[2]|0x20) == 'l' && (s[3]|0x20) == 'l' {
				return TokenKindNull, true
			}
		case 's':
			if (s[1]|0x20) == 'h' && (s[2]|0x20) == 'o' && (s[3]|0x20) == 'w' {
				return TokenKindShow, true
			}
		case 't':
			if (s[1]|0x20) == 'h' && (s[2]|0x20) == 'e' && (s[3]|0x20) == 'n' {
				return TokenKindThen, true
			}
			if (s[1]|0x20) == 'y' && (s[2]|0x20) == 'p' && (s[3]|0x20) == 'e' {
				return TokenKindType, true
			}
		case 'w':
			if (s[1]|0x20) == 'h' && (s[2]|0x20) == 'e' && (s[3]|0x20) == 'n' {
				return TokenKindWhen, true
			}
			if (s[1]|0x20) == 'i' && (s[2]|0x20) == 't' && (s[3]|0x20) == 'h' {
				return TokenKindWith, true
			}
		}
	case 5:
		switch s[0] | 0x20 {
		case 'a':
			if (s[1]|0x20) == 'c' && (s[2]|0x20) == 'o' && (s[3]|0x20) == 'r' && (s[4]|0x20) == 'n' {
				return TokenKindAcorn, true
			}
			if (s[1]|0x20) == 'f' && (s[2]|0x20) == 't' && (s[3]|0x20) == 'e' && (s[4]|0x20) == 'r' {
				return TokenKindAfter, true
			}
			if (s[1]|0x20) == 'l' && (s[2]|0x20) == 't' && (s[3]|0x20) == 'e' && (s[4]|0x20) == 'r' {
				return TokenKindAlter, true
			}
		case 'b':
			if (s[1]|0x20) == 'o' && (s[2]|0x20) == 'o' && (s[3]|0x20) == 's' && (s[4]|0x20) == 't' {
				return TokenKindBoost, true
			}
		case 'd':
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 'n' && (s[3]|0x20) == 's' && (s[4]|0x20) == 'e' {
				return TokenKindDense, true
			}
		case 'e':
			if (s[1]|0x20) == 'm' && (s[2]|0x20) == 'p' && (s[3]|0x20) == 't' && (s[4]|0x20) == 'y' {
				return TokenKindEmpty, true
			}
			if (s[1]|0x20) == 'x' && (s[2]|0x20) == 'a' && (s[3]|0x20) == 'c' && (s[4]|0x20) == 't' {
				return TokenKindExact, true
			}
		case 'g':
			if (s[1]|0x20) == 'r' && (s[2]|0x20) == 'o' && (s[3]|0x20) == 'u' && (s[4]|0x20) == 'p' {
				return TokenKindGroup, true
			}
		case 'i':
			if (s[1]|0x20) == 'n' && (s[2]|0x20) == 'd' && (s[3]|0x20) == 'e' && (s[4]|0x20) == 'x' {
				return TokenKindIndex, true
			}
		case 'l':
			if (s[1]|0x20) == 'i' && (s[2]|0x20) == 'm' && (s[3]|0x20) == 'i' && (s[4]|0x20) == 't' {
				return TokenKindLimit, true
			}
		case 'm':
			if (s[1]|0x20) == 'a' && (s[2]|0x20) == 't' && (s[3]|0x20) == 'c' && (s[4]|0x20) == 'h' {
				return TokenKindMatch, true
			}
			if (s[1]|0x20) == 'o' && (s[2]|0x20) == 'd' && (s[3]|0x20) == 'e' && (s[4]|0x20) == 'l' {
				return TokenKindModel, true
			}
		case 'o':
			if (s[1]|0x20) == 'r' && (s[2]|0x20) == 'd' && (s[3]|0x20) == 'e' && (s[4]|0x20) == 'r' {
				return TokenKindOrder, true
			}
		case 'p':
			if (s[1]|0x20) == 'a' && (s[2]|0x20) == 'i' && (s[3]|0x20) == 'r' && (s[4]|0x20) == 's' {
				return TokenKindPairs, true
			}
		case 'q':
			if (s[1]|0x20) == 'u' && (s[2]|0x20) == 'e' && (s[3]|0x20) == 'r' && (s[4]|0x20) == 'y' {
				return TokenKindQuery, true
			}
		case 's':
			if (s[1]|0x20) == 'c' && (s[2]|0x20) == 'o' && (s[3]|0x20) == 'r' && (s[4]|0x20) == 'e' {
				return TokenKindScore, true
			}
		case 't':
			if (s[1]|0x20) == 'u' && (s[2]|0x20) == 'r' && (s[3]|0x20) == 'b' && (s[4]|0x20) == 'o' {
				return TokenKindTurbo, true
			}
		case 'u':
			if (s[1]|0x20) == 's' && (s[2]|0x20) == 'i' && (s[3]|0x20) == 'n' && (s[4]|0x20) == 'g' {
				return TokenKindUsing, true
			}
		case 'w':
			if (s[1]|0x20) == 'h' && (s[2]|0x20) == 'e' && (s[3]|0x20) == 'r' && (s[4]|0x20) == 'e' {
				return TokenKindWhere, true
			}
		}
	case 6:
		switch s[0] | 0x20 {
		case 'a':
			if (s[1]|0x20) == 'l' && (s[2]|0x20) == 'w' && (s[3]|0x20) == 'a' && (s[4]|0x20) == 'y' && (s[5]|0x20) == 's' {
				return TokenKindAlways, true
			}
		case 'b':
			if (s[1]|0x20) == 'i' && (s[2]|0x20) == 'n' && (s[3]|0x20) == 'a' && (s[4]|0x20) == 'r' && (s[5]|0x20) == 'y' {
				return TokenKindBinary, true
			}
		case 'c':
			if (s[1]|0x20) == 'o' && (s[2]|0x20) == 's' && (s[3]|0x20) == 'i' && (s[4]|0x20) == 'n' && (s[5]|0x20) == 'e' {
				return TokenKindCosine, true
			}
			if (s[1]|0x20) == 'r' && (s[2]|0x20) == 'e' && (s[3]|0x20) == 'a' && (s[4]|0x20) == 't' && (s[5]|0x20) == 'e' {
				return TokenKindCreate, true
			}
		case 'd':
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 'l' && (s[3]|0x20) == 'e' && (s[4]|0x20) == 't' && (s[5]|0x20) == 'e' {
				return TokenKindDelete, true
			}
		case 'e':
			if (s[1]|0x20) == 'u' && (s[2]|0x20) == 'c' && (s[3]|0x20) == 'l' && (s[4]|0x20) == 'i' && (s[5]|0x20) == 'd' {
				return TokenKindEuclid, true
			}
		case 'f':
			if (s[1]|0x20) == 'u' && (s[2]|0x20) == 's' && (s[3]|0x20) == 'i' && (s[4]|0x20) == 'o' && (s[5]|0x20) == 'n' {
				return TokenKindFusion, true
			}
		case 'h':
			if (s[1]|0x20) == 'y' && (s[2]|0x20) == 'b' && (s[3]|0x20) == 'r' && (s[4]|0x20) == 'i' && (s[5]|0x20) == 'd' {
				return TokenKindHybrid, true
			}
		case 'i':
			if (s[1]|0x20) == 'n' && (s[2]|0x20) == 's' && (s[3]|0x20) == 'e' && (s[4]|0x20) == 'r' && (s[5]|0x20) == 't' {
				return TokenKindInsert, true
			}
		case 'l':
			if (s[1]|0x20) == 'o' && (s[2]|0x20) == 'o' && (s[3]|0x20) == 'k' && (s[4]|0x20) == 'u' && (s[5]|0x20) == 'p' {
				return TokenKindLookup, true
			}
		case 'o':
			if (s[1]|0x20) == 'f' && (s[2]|0x20) == 'f' && (s[3]|0x20) == 's' && (s[4]|0x20) == 'e' && (s[5]|0x20) == 't' {
				return TokenKindOffset, true
			}
		case 'p':
			if (s[1]|0x20) == 'a' && (s[2]|0x20) == 'r' && (s[3]|0x20) == 'a' && (s[4]|0x20) == 'm' && (s[5]|0x20) == 's' {
				return TokenKindParams, true
			}
			if (s[1]|0x20) == 'h' && (s[2]|0x20) == 'r' && (s[3]|0x20) == 'a' && (s[4]|0x20) == 's' && (s[5]|0x20) == 'e' {
				return TokenKindPhrase, true
			}
		case 'r':
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 'r' && (s[3]|0x20) == 'a' && (s[4]|0x20) == 'n' && (s[5]|0x20) == 'k' {
				return TokenKindRerank, true
			}
		case 's':
			if (s[1]|0x20) == 'a' && (s[2]|0x20) == 'm' && (s[3]|0x20) == 'p' && (s[4]|0x20) == 'l' && (s[5]|0x20) == 'e' {
				return TokenKindSample, true
			}
			if (s[1]|0x20) == 'c' && (s[2]|0x20) == 'a' && (s[3]|0x20) == 'l' && (s[4]|0x20) == 'a' && (s[5]|0x20) == 'r' {
				return TokenKindScalar, true
			}
			if (s[1]|0x20) == 'c' && (s[2]|0x20) == 'r' && (s[3]|0x20) == 'o' && (s[4]|0x20) == 'l' && (s[5]|0x20) == 'l' {
				return TokenKindScroll, true
			}
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 'l' && (s[3]|0x20) == 'e' && (s[4]|0x20) == 'c' && (s[5]|0x20) == 't' {
				return TokenKindSelect, true
			}
			if (s[1]|0x20) == 'p' && (s[2]|0x20) == 'a' && (s[3]|0x20) == 'r' && (s[4]|0x20) == 's' && (s[5]|0x20) == 'e' {
				return TokenKindSparse, true
			}
		case 't':
			if (s[1]|0x20) == 'a' && (s[2]|0x20) == 'r' && (s[3]|0x20) == 'g' && (s[4]|0x20) == 'e' && (s[5]|0x20) == 't' {
				return TokenKindTarget, true
			}
		case 'u':
			if (s[1]|0x20) == 'p' && (s[2]|0x20) == 'd' && (s[3]|0x20) == 'a' && (s[4]|0x20) == 't' && (s[5]|0x20) == 'e' {
				return TokenKindUpdate, true
			}
		case 'v':
			if (s[1]|0x20) == 'a' && (s[2]|0x20) == 'l' && (s[3]|0x20) == 'u' && (s[4]|0x20) == 'e' && (s[5]|0x20) == 's' {
				return TokenKindValues, true
			}
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 'c' && (s[3]|0x20) == 't' && (s[4]|0x20) == 'o' && (s[5]|0x20) == 'r' {
				return TokenKindVector, true
			}
		}
	case 7:
		switch s[0] | 0x20 {
		case 'b':
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 't' && (s[3]|0x20) == 'w' && (s[4]|0x20) == 'e' && (s[5]|0x20) == 'e' && (s[6]|0x20) == 'n' {
				return TokenKindBetween, true
			}
		case 'c':
			if (s[1]|0x20) == 'o' && (s[2]|0x20) == 'n' && (s[3]|0x20) == 't' && (s[4]|0x20) == 'e' && (s[5]|0x20) == 'x' && (s[6]|0x20) == 't' {
				return TokenKindContext, true
			}
		case 'n':
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 'a' && (s[3]|0x20) == 'r' && (s[4]|0x20) == 'e' && (s[5]|0x20) == 's' && (s[6]|0x20) == 't' {
				return TokenKindNearest, true
			}
		case 'p':
			if (s[1]|0x20) == 'a' && (s[2]|0x20) == 'y' && (s[3]|0x20) == 'l' && (s[4]|0x20) == 'o' && (s[5]|0x20) == 'a' && (s[6]|0x20) == 'd' {
				return TokenKindPayload, true
			}
			if (s[1]|0x20) == 'r' && (s[2]|0x20) == 'o' && (s[3]|0x20) == 'd' && (s[4]|0x20) == 'u' && (s[5]|0x20) == 'c' && (s[6]|0x20) == 't' {
				return TokenKindProduct, true
			}
		case 'v':
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 'c' && (s[3]|0x20) == 't' && (s[4]|0x20) == 'o' && (s[5]|0x20) == 'r' && (s[6]|0x20) == 's' {
				return TokenKindVectors, true
			}
		}
	case 8:
		switch s[0] | 0x20 {
		case 'd':
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 'f' && (s[3]|0x20) == 'a' && (s[4]|0x20) == 'u' && (s[5]|0x20) == 'l' && (s[6]|0x20) == 't' && (s[7]|0x20) == 's' {
				return TokenKindDefaults, true
			}
			if (s[1]|0x20) == 'i' && (s[2]|0x20) == 's' && (s[3]|0x20) == 'a' && (s[4]|0x20) == 'b' && (s[5]|0x20) == 'l' && (s[6]|0x20) == 'e' && (s[7]|0x20) == 'd' {
				return TokenKindDisabled, true
			}
			if (s[1]|0x20) == 'i' && (s[2]|0x20) == 's' && (s[3]|0x20) == 'c' && (s[4]|0x20) == 'o' && (s[5]|0x20) == 'v' && (s[6]|0x20) == 'e' && (s[7]|0x20) == 'r' {
				return TokenKindDiscover, true
			}
		case 'f':
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 'e' && (s[3]|0x20) == 'd' && (s[4]|0x20) == 'b' && (s[5]|0x20) == 'a' && (s[6]|0x20) == 'c' && (s[7]|0x20) == 'k' {
				return TokenKindFeedback, true
			}
		case 'g':
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 'o' && s[3] == '_' && (s[4]|0x20) == 'b' && (s[5]|0x20) == 'b' && (s[6]|0x20) == 'o' && (s[7]|0x20) == 'x' {
				return TokenKindGeoBbox, true
			}
		case 'p':
			if (s[1]|0x20) == 'r' && (s[2]|0x20) == 'e' && (s[3]|0x20) == 'f' && (s[4]|0x20) == 'e' && (s[5]|0x20) == 't' && (s[6]|0x20) == 'c' && (s[7]|0x20) == 'h' {
				return TokenKindPrefetch, true
			}
		case 'q':
			if (s[1]|0x20) == 'u' && (s[2]|0x20) == 'a' && (s[3]|0x20) == 'n' && (s[4]|0x20) == 't' && (s[5]|0x20) == 'i' && (s[6]|0x20) == 'l' && (s[7]|0x20) == 'e' {
				return TokenKindQuantile, true
			}
			if (s[1]|0x20) == 'u' && (s[2]|0x20) == 'a' && (s[3]|0x20) == 'n' && (s[4]|0x20) == 't' && (s[5]|0x20) == 'i' && (s[6]|0x20) == 'z' && (s[7]|0x20) == 'e' {
				return TokenKindQuantize, true
			}
		case 's':
			if (s[1]|0x20) == 't' && (s[2]|0x20) == 'r' && (s[3]|0x20) == 'a' && (s[4]|0x20) == 't' && (s[5]|0x20) == 'e' && (s[6]|0x20) == 'g' && (s[7]|0x20) == 'y' {
				return TokenKindStrategy, true
			}
		}
	case 9:
		switch s[0] | 0x20 {
		case 'm':
			if (s[1]|0x20) == 'a' && (s[2]|0x20) == 'n' && (s[3]|0x20) == 'h' && (s[4]|0x20) == 'a' && (s[5]|0x20) == 't' && (s[6]|0x20) == 't' && (s[7]|0x20) == 'a' && (s[8]|0x20) == 'n' {
				return TokenKindManhattan, true
			}
		case 'r':
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 'c' && (s[3]|0x20) == 'o' && (s[4]|0x20) == 'm' && (s[5]|0x20) == 'm' && (s[6]|0x20) == 'e' && (s[7]|0x20) == 'n' && (s[8]|0x20) == 'd' {
				return TokenKindRecommend, true
			}
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 'l' && (s[3]|0x20) == 'e' && (s[4]|0x20) == 'v' && (s[5]|0x20) == 'a' && (s[6]|0x20) == 'n' && (s[7]|0x20) == 'c' && (s[8]|0x20) == 'e' {
				return TokenKindRelevance, true
			}
		case 't':
			if (s[1]|0x20) == 'h' && (s[2]|0x20) == 'r' && (s[3]|0x20) == 'e' && (s[4]|0x20) == 's' && (s[5]|0x20) == 'h' && (s[6]|0x20) == 'o' && (s[7]|0x20) == 'l' && (s[8]|0x20) == 'd' {
				return TokenKindThreshold, true
			}
		}
	case 10:
		switch s[0] | 0x20 {
		case 'c':
			if (s[1]|0x20) == 'o' && (s[2]|0x20) == 'l' && (s[3]|0x20) == 'l' && (s[4]|0x20) == 'e' && (s[5]|0x20) == 'c' && (s[6]|0x20) == 't' && (s[7]|0x20) == 'i' && (s[8]|0x20) == 'o' && (s[9]|0x20) == 'n' {
				return TokenKindCollection, true
			}
		case 'g':
			if (s[1]|0x20) == 'e' && (s[2]|0x20) == 'o' && s[3] == '_' && (s[4]|0x20) == 'r' && (s[5]|0x20) == 'a' && (s[6]|0x20) == 'd' && (s[7]|0x20) == 'i' && (s[8]|0x20) == 'u' && (s[9]|0x20) == 's' {
				return TokenKindGeoRadius, true
			}
			if (s[1]|0x20) == 'r' && (s[2]|0x20) == 'o' && (s[3]|0x20) == 'u' && (s[4]|0x20) == 'p' && s[5] == '_' && (s[6]|0x20) == 's' && (s[7]|0x20) == 'i' && (s[8]|0x20) == 'z' && (s[9]|0x20) == 'e' {
				return TokenKindGroupSize, true
			}
		case 'h':
			if (s[1]|0x20) == 'a' && (s[2]|0x20) == 's' && s[3] == '_' && (s[4]|0x20) == 'v' && (s[5]|0x20) == 'e' && (s[6]|0x20) == 'c' && (s[7]|0x20) == 't' && (s[8]|0x20) == 'o' && (s[9]|0x20) == 'r' {
				return TokenKindHasVector, true
			}
		case 'o':
			if (s[1]|0x20) == 'p' && (s[2]|0x20) == 't' && (s[3]|0x20) == 'i' && (s[4]|0x20) == 'm' && (s[5]|0x20) == 'i' && (s[6]|0x20) == 'z' && (s[7]|0x20) == 'e' && (s[8]|0x20) == 'r' && (s[9]|0x20) == 's' {
				return TokenKindOptimizers, true
			}
		}
	case 11:
		switch s[0] | 0x20 {
		case 'c':
			if (s[1]|0x20) == 'o' && (s[2]|0x20) == 'l' && (s[3]|0x20) == 'l' && (s[4]|0x20) == 'e' && (s[5]|0x20) == 'c' && (s[6]|0x20) == 't' && (s[7]|0x20) == 'i' && (s[8]|0x20) == 'o' && (s[9]|0x20) == 'n' && (s[10]|0x20) == 's' {
				return TokenKindCollections, true
			}
		}
	case 12:
		switch s[0] | 0x20 {
		case 'v':
			if (s[1]|0x20) == 'a' && (s[2]|0x20) == 'l' && (s[3]|0x20) == 'u' && (s[4]|0x20) == 'e' && (s[5]|0x20) == 's' && s[6] == '_' && (s[7]|0x20) == 'c' && (s[8]|0x20) == 'o' && (s[9]|0x20) == 'u' && (s[10]|0x20) == 'n' && (s[11]|0x20) == 't' {
				return TokenKindValuesCount, true
			}
		}
	}
	return 0, false
}
