// Code generated by generate.go. DO NOT EDIT.
package lexer

// lookupKeywordFast is a generated case-insensitive keyword lookup
func lookupKeywordFast(s string) (TokenKind, bool) {
	switch len(s) {
	case 2:
		// AS
		if (s[0] == 'A' || s[0] == 'a') && (s[1] == 'S' || s[1] == 's') {
			return TokenKindAs, true
		}
		// BY
		if (s[0] == 'B' || s[0] == 'b') && (s[1] == 'Y' || s[1] == 'y') {
			return TokenKindBy, true
		}
		// ID
		if (s[0] == 'I' || s[0] == 'i') && (s[1] == 'D' || s[1] == 'd') {
			return TokenKindId, true
		}
		// ON
		if (s[0] == 'O' || s[0] == 'o') && (s[1] == 'N' || s[1] == 'n') {
			return TokenKindOn, true
		}
		// OR
		if (s[0] == 'O' || s[0] == 'o') && (s[1] == 'R' || s[1] == 'r') {
			return TokenKindOr, true
		}
		// IN
		if (s[0] == 'I' || s[0] == 'i') && (s[1] == 'N' || s[1] == 'n') {
			return TokenKindIn, true
		}
		// IS
		if (s[0] == 'I' || s[0] == 'i') && (s[1] == 'S' || s[1] == 's') {
			return TokenKindIs, true
		}
	case 3:
		// END
		if (s[0] == 'E' || s[0] == 'e') && (s[1] == 'N' || s[1] == 'n') && (s[2] == 'D' || s[2] == 'd') {
			return TokenKindEnd, true
		}
		// RAM
		if (s[0] == 'R' || s[0] == 'r') && (s[1] == 'A' || s[1] == 'a') && (s[2] == 'M' || s[2] == 'm') {
			return TokenKindRam, true
		}
		// ASC
		if (s[0] == 'A' || s[0] == 'a') && (s[1] == 'S' || s[1] == 's') && (s[2] == 'C' || s[2] == 'c') {
			return TokenKindAsc, true
		}
		// SET
		if (s[0] == 'S' || s[0] == 's') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'T' || s[2] == 't') {
			return TokenKindSet, true
		}
		// FOR
		if (s[0] == 'F' || s[0] == 'f') && (s[1] == 'O' || s[1] == 'o') && (s[2] == 'R' || s[2] == 'r') {
			return TokenKindFor, true
		}
		// AND
		if (s[0] == 'A' || s[0] == 'a') && (s[1] == 'N' || s[1] == 'n') && (s[2] == 'D' || s[2] == 'd') {
			return TokenKindAnd, true
		}
		// NOT
		if (s[0] == 'N' || s[0] == 'n') && (s[1] == 'O' || s[1] == 'o') && (s[2] == 'T' || s[2] == 't') {
			return TokenKindNot, true
		}
		// ANY
		if (s[0] == 'A' || s[0] == 'a') && (s[1] == 'N' || s[1] == 'n') && (s[2] == 'Y' || s[2] == 'y') {
			return TokenKindAny, true
		}
		// DOT
		if (s[0] == 'D' || s[0] == 'd') && (s[1] == 'O' || s[1] == 'o') && (s[2] == 'T' || s[2] == 't') {
			return TokenKindDot, true
		}
	case 4:
		// CASE
		if (s[0] == 'C' || s[0] == 'c') && (s[1] == 'A' || s[1] == 'a') && (s[2] == 'S' || s[2] == 's') && (s[3] == 'E' || s[3] == 'e') {
			return TokenKindCase, true
		}
		// WHEN
		if (s[0] == 'W' || s[0] == 'w') && (s[1] == 'H' || s[1] == 'h') && (s[2] == 'E' || s[2] == 'e') && (s[3] == 'N' || s[3] == 'n') {
			return TokenKindWhen, true
		}
		// THEN
		if (s[0] == 'T' || s[0] == 't') && (s[1] == 'H' || s[1] == 'h') && (s[2] == 'E' || s[2] == 'e') && (s[3] == 'N' || s[3] == 'n') {
			return TokenKindThen, true
		}
		// ELSE
		if (s[0] == 'E' || s[0] == 'e') && (s[1] == 'L' || s[1] == 'l') && (s[2] == 'S' || s[2] == 's') && (s[3] == 'E' || s[3] == 'e') {
			return TokenKindElse, true
		}
		// INTO
		if (s[0] == 'I' || s[0] == 'i') && (s[1] == 'N' || s[1] == 'n') && (s[2] == 'T' || s[2] == 't') && (s[3] == 'O' || s[3] == 'o') {
			return TokenKindInto, true
		}
		// WITH
		if (s[0] == 'W' || s[0] == 'w') && (s[1] == 'I' || s[1] == 'i') && (s[2] == 'T' || s[2] == 't') && (s[3] == 'H' || s[3] == 'h') {
			return TokenKindWith, true
		}
		// BITS
		if (s[0] == 'B' || s[0] == 'b') && (s[1] == 'I' || s[1] == 'i') && (s[2] == 'T' || s[2] == 't') && (s[3] == 'S' || s[3] == 's') {
			return TokenKindBits, true
		}
		// HNSW
		if (s[0] == 'H' || s[0] == 'h') && (s[1] == 'N' || s[1] == 'n') && (s[2] == 'S' || s[2] == 's') && (s[3] == 'W' || s[3] == 'w') {
			return TokenKindHnsw, true
		}
		// DROP
		if (s[0] == 'D' || s[0] == 'd') && (s[1] == 'R' || s[1] == 'r') && (s[2] == 'O' || s[2] == 'o') && (s[3] == 'P' || s[3] == 'p') {
			return TokenKindDrop, true
		}
		// SHOW
		if (s[0] == 'S' || s[0] == 's') && (s[1] == 'H' || s[1] == 'h') && (s[2] == 'O' || s[2] == 'o') && (s[3] == 'W' || s[3] == 'w') {
			return TokenKindShow, true
		}
		// DESC
		if (s[0] == 'D' || s[0] == 'd') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'S' || s[2] == 's') && (s[3] == 'C' || s[3] == 'c') {
			return TokenKindDesc, true
		}
		// FROM
		if (s[0] == 'F' || s[0] == 'f') && (s[1] == 'R' || s[1] == 'r') && (s[2] == 'O' || s[2] == 'o') && (s[3] == 'M' || s[3] == 'm') {
			return TokenKindFrom, true
		}
		// TYPE
		if (s[0] == 'T' || s[0] == 't') && (s[1] == 'Y' || s[1] == 'y') && (s[2] == 'P' || s[2] == 'p') && (s[3] == 'E' || s[3] == 'e') {
			return TokenKindType, true
		}
		// NULL
		if (s[0] == 'N' || s[0] == 'n') && (s[1] == 'U' || s[1] == 'u') && (s[2] == 'L' || s[2] == 'l') && (s[3] == 'L' || s[3] == 'l') {
			return TokenKindNull, true
		}
	case 5:
		// BOOST
		if (s[0] == 'B' || s[0] == 'b') && (s[1] == 'O' || s[1] == 'o') && (s[2] == 'O' || s[2] == 'o') && (s[3] == 'S' || s[3] == 's') && (s[4] == 'T' || s[4] == 't') {
			return TokenKindBoost, true
		}
		// USING
		if (s[0] == 'U' || s[0] == 'u') && (s[1] == 'S' || s[1] == 's') && (s[2] == 'I' || s[2] == 'i') && (s[3] == 'N' || s[3] == 'n') && (s[4] == 'G' || s[4] == 'g') {
			return TokenKindUsing, true
		}
		// MODEL
		if (s[0] == 'M' || s[0] == 'm') && (s[1] == 'O' || s[1] == 'o') && (s[2] == 'D' || s[2] == 'd') && (s[3] == 'E' || s[3] == 'e') && (s[4] == 'L' || s[4] == 'l') {
			return TokenKindModel, true
		}
		// DENSE
		if (s[0] == 'D' || s[0] == 'd') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'N' || s[2] == 'n') && (s[3] == 'S' || s[3] == 's') && (s[4] == 'E' || s[4] == 'e') {
			return TokenKindDense, true
		}
		// EXACT
		if (s[0] == 'E' || s[0] == 'e') && (s[1] == 'X' || s[1] == 'x') && (s[2] == 'A' || s[2] == 'a') && (s[3] == 'C' || s[3] == 'c') && (s[4] == 'T' || s[4] == 't') {
			return TokenKindExact, true
		}
		// ACORN
		if (s[0] == 'A' || s[0] == 'a') && (s[1] == 'C' || s[1] == 'c') && (s[2] == 'O' || s[2] == 'o') && (s[3] == 'R' || s[3] == 'r') && (s[4] == 'N' || s[4] == 'n') {
			return TokenKindAcorn, true
		}
		// TURBO
		if (s[0] == 'T' || s[0] == 't') && (s[1] == 'U' || s[1] == 'u') && (s[2] == 'R' || s[2] == 'r') && (s[3] == 'B' || s[3] == 'b') && (s[4] == 'O' || s[4] == 'o') {
			return TokenKindTurbo, true
		}
		// ALTER
		if (s[0] == 'A' || s[0] == 'a') && (s[1] == 'L' || s[1] == 'l') && (s[2] == 'T' || s[2] == 't') && (s[3] == 'E' || s[3] == 'e') && (s[4] == 'R' || s[4] == 'r') {
			return TokenKindAlter, true
		}
		// AFTER
		if (s[0] == 'A' || s[0] == 'a') && (s[1] == 'F' || s[1] == 'f') && (s[2] == 'T' || s[2] == 't') && (s[3] == 'E' || s[3] == 'e') && (s[4] == 'R' || s[4] == 'r') {
			return TokenKindAfter, true
		}
		// QUERY
		if (s[0] == 'Q' || s[0] == 'q') && (s[1] == 'U' || s[1] == 'u') && (s[2] == 'E' || s[2] == 'e') && (s[3] == 'R' || s[3] == 'r') && (s[4] == 'Y' || s[4] == 'y') {
			return TokenKindQuery, true
		}
		// PAIRS
		if (s[0] == 'P' || s[0] == 'p') && (s[1] == 'A' || s[1] == 'a') && (s[2] == 'I' || s[2] == 'i') && (s[3] == 'R' || s[3] == 'r') && (s[4] == 'S' || s[4] == 's') {
			return TokenKindPairs, true
		}
		// ORDER
		if (s[0] == 'O' || s[0] == 'o') && (s[1] == 'R' || s[1] == 'r') && (s[2] == 'D' || s[2] == 'd') && (s[3] == 'E' || s[3] == 'e') && (s[4] == 'R' || s[4] == 'r') {
			return TokenKindOrder, true
		}
		// LIMIT
		if (s[0] == 'L' || s[0] == 'l') && (s[1] == 'I' || s[1] == 'i') && (s[2] == 'M' || s[2] == 'm') && (s[3] == 'I' || s[3] == 'i') && (s[4] == 'T' || s[4] == 't') {
			return TokenKindLimit, true
		}
		// GROUP
		if (s[0] == 'G' || s[0] == 'g') && (s[1] == 'R' || s[1] == 'r') && (s[2] == 'O' || s[2] == 'o') && (s[3] == 'U' || s[3] == 'u') && (s[4] == 'P' || s[4] == 'p') {
			return TokenKindGroup, true
		}
		// WHERE
		if (s[0] == 'W' || s[0] == 'w') && (s[1] == 'H' || s[1] == 'h') && (s[2] == 'E' || s[2] == 'e') && (s[3] == 'R' || s[3] == 'r') && (s[4] == 'E' || s[4] == 'e') {
			return TokenKindWhere, true
		}
		// INDEX
		if (s[0] == 'I' || s[0] == 'i') && (s[1] == 'N' || s[1] == 'n') && (s[2] == 'D' || s[2] == 'd') && (s[3] == 'E' || s[3] == 'e') && (s[4] == 'X' || s[4] == 'x') {
			return TokenKindIndex, true
		}
		// EMPTY
		if (s[0] == 'E' || s[0] == 'e') && (s[1] == 'M' || s[1] == 'm') && (s[2] == 'P' || s[2] == 'p') && (s[3] == 'T' || s[3] == 't') && (s[4] == 'Y' || s[4] == 'y') {
			return TokenKindEmpty, true
		}
		// MATCH
		if (s[0] == 'M' || s[0] == 'm') && (s[1] == 'A' || s[1] == 'a') && (s[2] == 'T' || s[2] == 't') && (s[3] == 'C' || s[3] == 'c') && (s[4] == 'H' || s[4] == 'h') {
			return TokenKindMatch, true
		}
		// SCORE
		if (s[0] == 'S' || s[0] == 's') && (s[1] == 'C' || s[1] == 'c') && (s[2] == 'O' || s[2] == 'o') && (s[3] == 'R' || s[3] == 'r') && (s[4] == 'E' || s[4] == 'e') {
			return TokenKindScore, true
		}
	case 6:
		// INSERT
		if (s[0] == 'I' || s[0] == 'i') && (s[1] == 'N' || s[1] == 'n') && (s[2] == 'S' || s[2] == 's') && (s[3] == 'E' || s[3] == 'e') && (s[4] == 'R' || s[4] == 'r') && (s[5] == 'T' || s[5] == 't') {
			return TokenKindInsert, true
		}
		// VALUES
		if (s[0] == 'V' || s[0] == 'v') && (s[1] == 'A' || s[1] == 'a') && (s[2] == 'L' || s[2] == 'l') && (s[3] == 'U' || s[3] == 'u') && (s[4] == 'E' || s[4] == 'e') && (s[5] == 'S' || s[5] == 's') {
			return TokenKindValues, true
		}
		// HYBRID
		if (s[0] == 'H' || s[0] == 'h') && (s[1] == 'Y' || s[1] == 'y') && (s[2] == 'B' || s[2] == 'b') && (s[3] == 'R' || s[3] == 'r') && (s[4] == 'I' || s[4] == 'i') && (s[5] == 'D' || s[5] == 'd') {
			return TokenKindHybrid, true
		}
		// SPARSE
		if (s[0] == 'S' || s[0] == 's') && (s[1] == 'P' || s[1] == 'p') && (s[2] == 'A' || s[2] == 'a') && (s[3] == 'R' || s[3] == 'r') && (s[4] == 'S' || s[4] == 's') && (s[5] == 'E' || s[5] == 'e') {
			return TokenKindSparse, true
		}
		// RERANK
		if (s[0] == 'R' || s[0] == 'r') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'R' || s[2] == 'r') && (s[3] == 'A' || s[3] == 'a') && (s[4] == 'N' || s[4] == 'n') && (s[5] == 'K' || s[5] == 'k') {
			return TokenKindRerank, true
		}
		// SCALAR
		if (s[0] == 'S' || s[0] == 's') && (s[1] == 'C' || s[1] == 'c') && (s[2] == 'A' || s[2] == 'a') && (s[3] == 'L' || s[3] == 'l') && (s[4] == 'A' || s[4] == 'a') && (s[5] == 'R' || s[5] == 'r') {
			return TokenKindScalar, true
		}
		// BINARY
		if (s[0] == 'B' || s[0] == 'b') && (s[1] == 'I' || s[1] == 'i') && (s[2] == 'N' || s[2] == 'n') && (s[3] == 'A' || s[3] == 'a') && (s[4] == 'R' || s[4] == 'r') && (s[5] == 'Y' || s[5] == 'y') {
			return TokenKindBinary, true
		}
		// ALWAYS
		if (s[0] == 'A' || s[0] == 'a') && (s[1] == 'L' || s[1] == 'l') && (s[2] == 'W' || s[2] == 'w') && (s[3] == 'A' || s[3] == 'a') && (s[4] == 'Y' || s[4] == 'y') && (s[5] == 'S' || s[5] == 's') {
			return TokenKindAlways, true
		}
		// PARAMS
		if (s[0] == 'P' || s[0] == 'p') && (s[1] == 'A' || s[1] == 'a') && (s[2] == 'R' || s[2] == 'r') && (s[3] == 'A' || s[3] == 'a') && (s[4] == 'M' || s[4] == 'm') && (s[5] == 'S' || s[5] == 's') {
			return TokenKindParams, true
		}
		// CREATE
		if (s[0] == 'C' || s[0] == 'c') && (s[1] == 'R' || s[1] == 'r') && (s[2] == 'E' || s[2] == 'e') && (s[3] == 'A' || s[3] == 'a') && (s[4] == 'T' || s[4] == 't') && (s[5] == 'E' || s[5] == 'e') {
			return TokenKindCreate, true
		}
		// SELECT
		if (s[0] == 'S' || s[0] == 's') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'L' || s[2] == 'l') && (s[3] == 'E' || s[3] == 'e') && (s[4] == 'C' || s[4] == 'c') && (s[5] == 'T' || s[5] == 't') {
			return TokenKindSelect, true
		}
		// SCROLL
		if (s[0] == 'S' || s[0] == 's') && (s[1] == 'C' || s[1] == 'c') && (s[2] == 'R' || s[2] == 'r') && (s[3] == 'O' || s[3] == 'o') && (s[4] == 'L' || s[4] == 'l') && (s[5] == 'L' || s[5] == 'l') {
			return TokenKindScroll, true
		}
		// TARGET
		if (s[0] == 'T' || s[0] == 't') && (s[1] == 'A' || s[1] == 'a') && (s[2] == 'R' || s[2] == 'r') && (s[3] == 'G' || s[3] == 'g') && (s[4] == 'E' || s[4] == 'e') && (s[5] == 'T' || s[5] == 't') {
			return TokenKindTarget, true
		}
		// DELETE
		if (s[0] == 'D' || s[0] == 'd') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'L' || s[2] == 'l') && (s[3] == 'E' || s[3] == 'e') && (s[4] == 'T' || s[4] == 't') && (s[5] == 'E' || s[5] == 'e') {
			return TokenKindDelete, true
		}
		// UPDATE
		if (s[0] == 'U' || s[0] == 'u') && (s[1] == 'P' || s[1] == 'p') && (s[2] == 'D' || s[2] == 'd') && (s[3] == 'A' || s[3] == 'a') && (s[4] == 'T' || s[4] == 't') && (s[5] == 'E' || s[5] == 'e') {
			return TokenKindUpdate, true
		}
		// VECTOR
		if (s[0] == 'V' || s[0] == 'v') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'C' || s[2] == 'c') && (s[3] == 'T' || s[3] == 't') && (s[4] == 'O' || s[4] == 'o') && (s[5] == 'R' || s[5] == 'r') {
			return TokenKindVector, true
		}
		// PHRASE
		if (s[0] == 'P' || s[0] == 'p') && (s[1] == 'H' || s[1] == 'h') && (s[2] == 'R' || s[2] == 'r') && (s[3] == 'A' || s[3] == 'a') && (s[4] == 'S' || s[4] == 's') && (s[5] == 'E' || s[5] == 'e') {
			return TokenKindPhrase, true
		}
		// OFFSET
		if (s[0] == 'O' || s[0] == 'o') && (s[1] == 'F' || s[1] == 'f') && (s[2] == 'F' || s[2] == 'f') && (s[3] == 'S' || s[3] == 's') && (s[4] == 'E' || s[4] == 'e') && (s[5] == 'T' || s[5] == 't') {
			return TokenKindOffset, true
		}
		// LOOKUP
		if (s[0] == 'L' || s[0] == 'l') && (s[1] == 'O' || s[1] == 'o') && (s[2] == 'O' || s[2] == 'o') && (s[3] == 'K' || s[3] == 'k') && (s[4] == 'U' || s[4] == 'u') && (s[5] == 'P' || s[5] == 'p') {
			return TokenKindLookup, true
		}
		// COSINE
		if (s[0] == 'C' || s[0] == 'c') && (s[1] == 'O' || s[1] == 'o') && (s[2] == 'S' || s[2] == 's') && (s[3] == 'I' || s[3] == 'i') && (s[4] == 'N' || s[4] == 'n') && (s[5] == 'E' || s[5] == 'e') {
			return TokenKindCosine, true
		}
		// EUCLID
		if (s[0] == 'E' || s[0] == 'e') && (s[1] == 'U' || s[1] == 'u') && (s[2] == 'C' || s[2] == 'c') && (s[3] == 'L' || s[3] == 'l') && (s[4] == 'I' || s[4] == 'i') && (s[5] == 'D' || s[5] == 'd') {
			return TokenKindEuclid, true
		}
		// FUSION
		if (s[0] == 'F' || s[0] == 'f') && (s[1] == 'U' || s[1] == 'u') && (s[2] == 'S' || s[2] == 's') && (s[3] == 'I' || s[3] == 'i') && (s[4] == 'O' || s[4] == 'o') && (s[5] == 'N' || s[5] == 'n') {
			return TokenKindFusion, true
		}
		// SAMPLE
		if (s[0] == 'S' || s[0] == 's') && (s[1] == 'A' || s[1] == 'a') && (s[2] == 'M' || s[2] == 'm') && (s[3] == 'P' || s[3] == 'p') && (s[4] == 'L' || s[4] == 'l') && (s[5] == 'E' || s[5] == 'e') {
			return TokenKindSample, true
		}
	case 7:
		// PRODUCT
		if (s[0] == 'P' || s[0] == 'p') && (s[1] == 'R' || s[1] == 'r') && (s[2] == 'O' || s[2] == 'o') && (s[3] == 'D' || s[3] == 'd') && (s[4] == 'U' || s[4] == 'u') && (s[5] == 'C' || s[5] == 'c') && (s[6] == 'T' || s[6] == 't') {
			return TokenKindProduct, true
		}
		// VECTORS
		if (s[0] == 'V' || s[0] == 'v') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'C' || s[2] == 'c') && (s[3] == 'T' || s[3] == 't') && (s[4] == 'O' || s[4] == 'o') && (s[5] == 'R' || s[5] == 'r') && (s[6] == 'S' || s[6] == 's') {
			return TokenKindVectors, true
		}
		// NEAREST
		if (s[0] == 'N' || s[0] == 'n') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'A' || s[2] == 'a') && (s[3] == 'R' || s[3] == 'r') && (s[4] == 'E' || s[4] == 'e') && (s[5] == 'S' || s[5] == 's') && (s[6] == 'T' || s[6] == 't') {
			return TokenKindNearest, true
		}
		// CONTEXT
		if (s[0] == 'C' || s[0] == 'c') && (s[1] == 'O' || s[1] == 'o') && (s[2] == 'N' || s[2] == 'n') && (s[3] == 'T' || s[3] == 't') && (s[4] == 'E' || s[4] == 'e') && (s[5] == 'X' || s[5] == 'x') && (s[6] == 'T' || s[6] == 't') {
			return TokenKindContext, true
		}
		// PAYLOAD
		if (s[0] == 'P' || s[0] == 'p') && (s[1] == 'A' || s[1] == 'a') && (s[2] == 'Y' || s[2] == 'y') && (s[3] == 'L' || s[3] == 'l') && (s[4] == 'O' || s[4] == 'o') && (s[5] == 'A' || s[5] == 'a') && (s[6] == 'D' || s[6] == 'd') {
			return TokenKindPayload, true
		}
		// BETWEEN
		if (s[0] == 'B' || s[0] == 'b') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'T' || s[2] == 't') && (s[3] == 'W' || s[3] == 'w') && (s[4] == 'E' || s[4] == 'e') && (s[5] == 'E' || s[5] == 'e') && (s[6] == 'N' || s[6] == 'n') {
			return TokenKindBetween, true
		}
	case 8:
		// GEO_BBOX
		if (s[0] == 'G' || s[0] == 'g') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'O' || s[2] == 'o') && s[3] == '_' && (s[4] == 'B' || s[4] == 'b') && (s[5] == 'B' || s[5] == 'b') && (s[6] == 'O' || s[6] == 'o') && (s[7] == 'X' || s[7] == 'x') {
			return TokenKindGeoBbox, true
		}
		// DEFAULTS
		if (s[0] == 'D' || s[0] == 'd') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'F' || s[2] == 'f') && (s[3] == 'A' || s[3] == 'a') && (s[4] == 'U' || s[4] == 'u') && (s[5] == 'L' || s[5] == 'l') && (s[6] == 'T' || s[6] == 't') && (s[7] == 'S' || s[7] == 's') {
			return TokenKindDefaults, true
		}
		// QUANTIZE
		if (s[0] == 'Q' || s[0] == 'q') && (s[1] == 'U' || s[1] == 'u') && (s[2] == 'A' || s[2] == 'a') && (s[3] == 'N' || s[3] == 'n') && (s[4] == 'T' || s[4] == 't') && (s[5] == 'I' || s[5] == 'i') && (s[6] == 'Z' || s[6] == 'z') && (s[7] == 'E' || s[7] == 'e') {
			return TokenKindQuantize, true
		}
		// QUANTILE
		if (s[0] == 'Q' || s[0] == 'q') && (s[1] == 'U' || s[1] == 'u') && (s[2] == 'A' || s[2] == 'a') && (s[3] == 'N' || s[3] == 'n') && (s[4] == 'T' || s[4] == 't') && (s[5] == 'I' || s[5] == 'i') && (s[6] == 'L' || s[6] == 'l') && (s[7] == 'E' || s[7] == 'e') {
			return TokenKindQuantile, true
		}
		// DISABLED
		if (s[0] == 'D' || s[0] == 'd') && (s[1] == 'I' || s[1] == 'i') && (s[2] == 'S' || s[2] == 's') && (s[3] == 'A' || s[3] == 'a') && (s[4] == 'B' || s[4] == 'b') && (s[5] == 'L' || s[5] == 'l') && (s[6] == 'E' || s[6] == 'e') && (s[7] == 'D' || s[7] == 'd') {
			return TokenKindDisabled, true
		}
		// DISCOVER
		if (s[0] == 'D' || s[0] == 'd') && (s[1] == 'I' || s[1] == 'i') && (s[2] == 'S' || s[2] == 's') && (s[3] == 'C' || s[3] == 'c') && (s[4] == 'O' || s[4] == 'o') && (s[5] == 'V' || s[5] == 'v') && (s[6] == 'E' || s[6] == 'e') && (s[7] == 'R' || s[7] == 'r') {
			return TokenKindDiscover, true
		}
		// STRATEGY
		if (s[0] == 'S' || s[0] == 's') && (s[1] == 'T' || s[1] == 't') && (s[2] == 'R' || s[2] == 'r') && (s[3] == 'A' || s[3] == 'a') && (s[4] == 'T' || s[4] == 't') && (s[5] == 'E' || s[5] == 'e') && (s[6] == 'G' || s[6] == 'g') && (s[7] == 'Y' || s[7] == 'y') {
			return TokenKindStrategy, true
		}
		// PREFETCH
		if (s[0] == 'P' || s[0] == 'p') && (s[1] == 'R' || s[1] == 'r') && (s[2] == 'E' || s[2] == 'e') && (s[3] == 'F' || s[3] == 'f') && (s[4] == 'E' || s[4] == 'e') && (s[5] == 'T' || s[5] == 't') && (s[6] == 'C' || s[6] == 'c') && (s[7] == 'H' || s[7] == 'h') {
			return TokenKindPrefetch, true
		}
		// FEEDBACK
		if (s[0] == 'F' || s[0] == 'f') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'E' || s[2] == 'e') && (s[3] == 'D' || s[3] == 'd') && (s[4] == 'B' || s[4] == 'b') && (s[5] == 'A' || s[5] == 'a') && (s[6] == 'C' || s[6] == 'c') && (s[7] == 'K' || s[7] == 'k') {
			return TokenKindFeedback, true
		}
	case 9:
		// RECOMMEND
		if (s[0] == 'R' || s[0] == 'r') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'C' || s[2] == 'c') && (s[3] == 'O' || s[3] == 'o') && (s[4] == 'M' || s[4] == 'm') && (s[5] == 'M' || s[5] == 'm') && (s[6] == 'E' || s[6] == 'e') && (s[7] == 'N' || s[7] == 'n') && (s[8] == 'D' || s[8] == 'd') {
			return TokenKindRecommend, true
		}
		// THRESHOLD
		if (s[0] == 'T' || s[0] == 't') && (s[1] == 'H' || s[1] == 'h') && (s[2] == 'R' || s[2] == 'r') && (s[3] == 'E' || s[3] == 'e') && (s[4] == 'S' || s[4] == 's') && (s[5] == 'H' || s[5] == 'h') && (s[6] == 'O' || s[6] == 'o') && (s[7] == 'L' || s[7] == 'l') && (s[8] == 'D' || s[8] == 'd') {
			return TokenKindThreshold, true
		}
		// MANHATTAN
		if (s[0] == 'M' || s[0] == 'm') && (s[1] == 'A' || s[1] == 'a') && (s[2] == 'N' || s[2] == 'n') && (s[3] == 'H' || s[3] == 'h') && (s[4] == 'A' || s[4] == 'a') && (s[5] == 'T' || s[5] == 't') && (s[6] == 'T' || s[6] == 't') && (s[7] == 'A' || s[7] == 'a') && (s[8] == 'N' || s[8] == 'n') {
			return TokenKindManhattan, true
		}
		// RELEVANCE
		if (s[0] == 'R' || s[0] == 'r') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'L' || s[2] == 'l') && (s[3] == 'E' || s[3] == 'e') && (s[4] == 'V' || s[4] == 'v') && (s[5] == 'A' || s[5] == 'a') && (s[6] == 'N' || s[6] == 'n') && (s[7] == 'C' || s[7] == 'c') && (s[8] == 'E' || s[8] == 'e') {
			return TokenKindRelevance, true
		}
	case 10:
		// GEO_RADIUS
		if (s[0] == 'G' || s[0] == 'g') && (s[1] == 'E' || s[1] == 'e') && (s[2] == 'O' || s[2] == 'o') && s[3] == '_' && (s[4] == 'R' || s[4] == 'r') && (s[5] == 'A' || s[5] == 'a') && (s[6] == 'D' || s[6] == 'd') && (s[7] == 'I' || s[7] == 'i') && (s[8] == 'U' || s[8] == 'u') && (s[9] == 'S' || s[9] == 's') {
			return TokenKindGeoRadius, true
		}
		// HAS_VECTOR
		if (s[0] == 'H' || s[0] == 'h') && (s[1] == 'A' || s[1] == 'a') && (s[2] == 'S' || s[2] == 's') && s[3] == '_' && (s[4] == 'V' || s[4] == 'v') && (s[5] == 'E' || s[5] == 'e') && (s[6] == 'C' || s[6] == 'c') && (s[7] == 'T' || s[7] == 't') && (s[8] == 'O' || s[8] == 'o') && (s[9] == 'R' || s[9] == 'r') {
			return TokenKindHasVector, true
		}
		// COLLECTION
		if (s[0] == 'C' || s[0] == 'c') && (s[1] == 'O' || s[1] == 'o') && (s[2] == 'L' || s[2] == 'l') && (s[3] == 'L' || s[3] == 'l') && (s[4] == 'E' || s[4] == 'e') && (s[5] == 'C' || s[5] == 'c') && (s[6] == 'T' || s[6] == 't') && (s[7] == 'I' || s[7] == 'i') && (s[8] == 'O' || s[8] == 'o') && (s[9] == 'N' || s[9] == 'n') {
			return TokenKindCollection, true
		}
		// OPTIMIZERS
		if (s[0] == 'O' || s[0] == 'o') && (s[1] == 'P' || s[1] == 'p') && (s[2] == 'T' || s[2] == 't') && (s[3] == 'I' || s[3] == 'i') && (s[4] == 'M' || s[4] == 'm') && (s[5] == 'I' || s[5] == 'i') && (s[6] == 'Z' || s[6] == 'z') && (s[7] == 'E' || s[7] == 'e') && (s[8] == 'R' || s[8] == 'r') && (s[9] == 'S' || s[9] == 's') {
			return TokenKindOptimizers, true
		}
		// GROUP_SIZE
		if (s[0] == 'G' || s[0] == 'g') && (s[1] == 'R' || s[1] == 'r') && (s[2] == 'O' || s[2] == 'o') && (s[3] == 'U' || s[3] == 'u') && (s[4] == 'P' || s[4] == 'p') && s[5] == '_' && (s[6] == 'S' || s[6] == 's') && (s[7] == 'I' || s[7] == 'i') && (s[8] == 'Z' || s[8] == 'z') && (s[9] == 'E' || s[9] == 'e') {
			return TokenKindGroupSize, true
		}
	case 11:
		// COLLECTIONS
		if (s[0] == 'C' || s[0] == 'c') && (s[1] == 'O' || s[1] == 'o') && (s[2] == 'L' || s[2] == 'l') && (s[3] == 'L' || s[3] == 'l') && (s[4] == 'E' || s[4] == 'e') && (s[5] == 'C' || s[5] == 'c') && (s[6] == 'T' || s[6] == 't') && (s[7] == 'I' || s[7] == 'i') && (s[8] == 'O' || s[8] == 'o') && (s[9] == 'N' || s[9] == 'n') && (s[10] == 'S' || s[10] == 's') {
			return TokenKindCollections, true
		}
	case 12:
		// VALUES_COUNT
		if (s[0] == 'V' || s[0] == 'v') && (s[1] == 'A' || s[1] == 'a') && (s[2] == 'L' || s[2] == 'l') && (s[3] == 'U' || s[3] == 'u') && (s[4] == 'E' || s[4] == 'e') && (s[5] == 'S' || s[5] == 's') && s[6] == '_' && (s[7] == 'C' || s[7] == 'c') && (s[8] == 'O' || s[8] == 'o') && (s[9] == 'U' || s[9] == 'u') && (s[10] == 'N' || s[10] == 'n') && (s[11] == 'T' || s[11] == 't') {
			return TokenKindValuesCount, true
		}
	}
	return 0, false
}
