// Code generated by gen_lexer.go; DO NOT EDIT.

package lexer

func lookupKeywordFast(b []byte) (TokenKind, bool) {
	switch string(b) {
	case "ACORN":
		return TokenKindAcorn, true
	case "AFTER":
		return TokenKindAfter, true
	case "ALTER":
		return TokenKindAlter, true
	case "ALWAYS":
		return TokenKindAlways, true
	case "AND":
		return TokenKindAnd, true
	case "ANY":
		return TokenKindAny, true
	case "AS":
		return TokenKindAs, true
	case "ASC":
		return TokenKindAsc, true
	case "BETWEEN":
		return TokenKindBetween, true
	case "BINARY":
		return TokenKindBinary, true
	case "BITS":
		return TokenKindBits, true
	case "BOOST":
		return TokenKindBoost, true
	case "BY":
		return TokenKindBy, true
	case "CASE":
		return TokenKindCase, true
	case "COLLECTION":
		return TokenKindCollection, true
	case "COLLECTIONS":
		return TokenKindCollections, true
	case "CONTEXT":
		return TokenKindContext, true
	case "COSINE":
		return TokenKindCosine, true
	case "CREATE":
		return TokenKindCreate, true
	case "DEFAULTS":
		return TokenKindDefaults, true
	case "DELETE":
		return TokenKindDelete, true
	case "DENSE":
		return TokenKindDense, true
	case "DESC":
		return TokenKindDesc, true
	case "DISABLED":
		return TokenKindDisabled, true
	case "DISCOVER":
		return TokenKindDiscover, true
	case "DOT":
		return TokenKindDot, true
	case "DROP":
		return TokenKindDrop, true
	case "ELSE":
		return TokenKindElse, true
	case "EMPTY":
		return TokenKindEmpty, true
	case "END":
		return TokenKindEnd, true
	case "EUCLID":
		return TokenKindEuclid, true
	case "EXACT":
		return TokenKindExact, true
	case "FOR":
		return TokenKindFor, true
	case "FROM":
		return TokenKindFrom, true
	case "FUSION":
		return TokenKindFusion, true
	case "GROUP":
		return TokenKindGroup, true
	case "GROUP_SIZE":
		return TokenKindGroupSize, true
	case "HNSW":
		return TokenKindHnsw, true
	case "HYBRID":
		return TokenKindHybrid, true
	case "ID":
		return TokenKindId, true
	case "IN":
		return TokenKindIn, true
	case "INDEX":
		return TokenKindIndex, true
	case "INSERT":
		return TokenKindInsert, true
	case "INTO":
		return TokenKindInto, true
	case "IS":
		return TokenKindIs, true
	case "LIMIT":
		return TokenKindLimit, true
	case "LOOKUP":
		return TokenKindLookup, true
	case "MANHATTAN":
		return TokenKindManhattan, true
	case "MATCH":
		return TokenKindMatch, true
	case "MODEL":
		return TokenKindModel, true
	case "NEAREST":
		return TokenKindNearest, true
	case "NOT":
		return TokenKindNot, true
	case "NULL":
		return TokenKindNull, true
	case "OFFSET":
		return TokenKindOffset, true
	case "ON":
		return TokenKindOn, true
	case "OPTIMIZERS":
		return TokenKindOptimizers, true
	case "OR":
		return TokenKindOr, true
	case "ORDER":
		return TokenKindOrder, true
	case "PAIRS":
		return TokenKindPairs, true
	case "PARAMS":
		return TokenKindParams, true
	case "PAYLOAD":
		return TokenKindPayload, true
	case "PHRASE":
		return TokenKindPhrase, true
	case "PREFETCH":
		return TokenKindPrefetch, true
	case "PRODUCT":
		return TokenKindProduct, true
	case "QUANTILE":
		return TokenKindQuantile, true
	case "QUANTIZE":
		return TokenKindQuantize, true
	case "QUERY":
		return TokenKindQuery, true
	case "RAM":
		return TokenKindRam, true
	case "RECOMMEND":
		return TokenKindRecommend, true
	case "RERANK":
		return TokenKindRerank, true
	case "SAMPLE":
		return TokenKindSample, true
	case "SCALAR":
		return TokenKindScalar, true
	case "SCORE":
		return TokenKindScore, true
	case "SCROLL":
		return TokenKindScroll, true
	case "SELECT":
		return TokenKindSelect, true
	case "SET":
		return TokenKindSet, true
	case "SHOW":
		return TokenKindShow, true
	case "SPARSE":
		return TokenKindSparse, true
	case "STRATEGY":
		return TokenKindStrategy, true
	case "TARGET":
		return TokenKindTarget, true
	case "THEN":
		return TokenKindThen, true
	case "THRESHOLD":
		return TokenKindThreshold, true
	case "TURBO":
		return TokenKindTurbo, true
	case "TYPE":
		return TokenKindType, true
	case "UPDATE":
		return TokenKindUpdate, true
	case "USING":
		return TokenKindUsing, true
	case "VALUES":
		return TokenKindValues, true
	case "VECTOR":
		return TokenKindVector, true
	case "VECTORS":
		return TokenKindVectors, true
	case "WHEN":
		return TokenKindWhen, true
	case "WHERE":
		return TokenKindWhere, true
	case "WITH":
		return TokenKindWith, true
	default:
		return 0, false
	}
}
