// Code generated by gen_lookup.go; DO NOT EDIT.
package lexer

func lookupKeywordFast(s string) (TokenKind, bool) {
	switch len(s) {
	case 2:
		if equalsCaseInsensitive(s, "AS") {
			return TokenKindAs, true
		}
		if equalsCaseInsensitive(s, "BY") {
			return TokenKindBy, true
		}
		if equalsCaseInsensitive(s, "ID") {
			return TokenKindId, true
		}
		if equalsCaseInsensitive(s, "IN") {
			return TokenKindIn, true
		}
		if equalsCaseInsensitive(s, "IS") {
			return TokenKindIs, true
		}
		if equalsCaseInsensitive(s, "ON") {
			return TokenKindOn, true
		}
		if equalsCaseInsensitive(s, "OR") {
			return TokenKindOr, true
		}
	case 3:
		if equalsCaseInsensitive(s, "AND") {
			return TokenKindAnd, true
		}
		if equalsCaseInsensitive(s, "ANY") {
			return TokenKindAny, true
		}
		if equalsCaseInsensitive(s, "ASC") {
			return TokenKindAsc, true
		}
		if equalsCaseInsensitive(s, "DOT") {
			return TokenKindDot, true
		}
		if equalsCaseInsensitive(s, "END") {
			return TokenKindEnd, true
		}
		if equalsCaseInsensitive(s, "FOR") {
			return TokenKindFor, true
		}
		if equalsCaseInsensitive(s, "NOT") {
			return TokenKindNot, true
		}
		if equalsCaseInsensitive(s, "RAM") {
			return TokenKindRam, true
		}
		if equalsCaseInsensitive(s, "SET") {
			return TokenKindSet, true
		}
	case 4:
		if equalsCaseInsensitive(s, "BITS") {
			return TokenKindBits, true
		}
		if equalsCaseInsensitive(s, "CASE") {
			return TokenKindCase, true
		}
		if equalsCaseInsensitive(s, "DESC") {
			return TokenKindDesc, true
		}
		if equalsCaseInsensitive(s, "DROP") {
			return TokenKindDrop, true
		}
		if equalsCaseInsensitive(s, "ELSE") {
			return TokenKindElse, true
		}
		if equalsCaseInsensitive(s, "FROM") {
			return TokenKindFrom, true
		}
		if equalsCaseInsensitive(s, "HNSW") {
			return TokenKindHnsw, true
		}
		if equalsCaseInsensitive(s, "INTO") {
			return TokenKindInto, true
		}
		if equalsCaseInsensitive(s, "NULL") {
			return TokenKindNull, true
		}
		if equalsCaseInsensitive(s, "SHOW") {
			return TokenKindShow, true
		}
		if equalsCaseInsensitive(s, "THEN") {
			return TokenKindThen, true
		}
		if equalsCaseInsensitive(s, "TYPE") {
			return TokenKindType, true
		}
		if equalsCaseInsensitive(s, "WHEN") {
			return TokenKindWhen, true
		}
		if equalsCaseInsensitive(s, "WITH") {
			return TokenKindWith, true
		}
	case 5:
		if equalsCaseInsensitive(s, "ACORN") {
			return TokenKindAcorn, true
		}
		if equalsCaseInsensitive(s, "AFTER") {
			return TokenKindAfter, true
		}
		if equalsCaseInsensitive(s, "ALTER") {
			return TokenKindAlter, true
		}
		if equalsCaseInsensitive(s, "BOOST") {
			return TokenKindBoost, true
		}
		if equalsCaseInsensitive(s, "DENSE") {
			return TokenKindDense, true
		}
		if equalsCaseInsensitive(s, "EMPTY") {
			return TokenKindEmpty, true
		}
		if equalsCaseInsensitive(s, "EXACT") {
			return TokenKindExact, true
		}
		if equalsCaseInsensitive(s, "GROUP") {
			return TokenKindGroup, true
		}
		if equalsCaseInsensitive(s, "INDEX") {
			return TokenKindIndex, true
		}
		if equalsCaseInsensitive(s, "LIMIT") {
			return TokenKindLimit, true
		}
		if equalsCaseInsensitive(s, "MATCH") {
			return TokenKindMatch, true
		}
		if equalsCaseInsensitive(s, "MODEL") {
			return TokenKindModel, true
		}
		if equalsCaseInsensitive(s, "ORDER") {
			return TokenKindOrder, true
		}
		if equalsCaseInsensitive(s, "PAIRS") {
			return TokenKindPairs, true
		}
		if equalsCaseInsensitive(s, "QUERY") {
			return TokenKindQuery, true
		}
		if equalsCaseInsensitive(s, "SCORE") {
			return TokenKindScore, true
		}
		if equalsCaseInsensitive(s, "TURBO") {
			return TokenKindTurbo, true
		}
		if equalsCaseInsensitive(s, "USING") {
			return TokenKindUsing, true
		}
		if equalsCaseInsensitive(s, "WHERE") {
			return TokenKindWhere, true
		}
	case 6:
		if equalsCaseInsensitive(s, "ALWAYS") {
			return TokenKindAlways, true
		}
		if equalsCaseInsensitive(s, "BINARY") {
			return TokenKindBinary, true
		}
		if equalsCaseInsensitive(s, "COSINE") {
			return TokenKindCosine, true
		}
		if equalsCaseInsensitive(s, "CREATE") {
			return TokenKindCreate, true
		}
		if equalsCaseInsensitive(s, "DELETE") {
			return TokenKindDelete, true
		}
		if equalsCaseInsensitive(s, "EUCLID") {
			return TokenKindEuclid, true
		}
		if equalsCaseInsensitive(s, "FUSION") {
			return TokenKindFusion, true
		}
		if equalsCaseInsensitive(s, "HYBRID") {
			return TokenKindHybrid, true
		}
		if equalsCaseInsensitive(s, "INSERT") {
			return TokenKindInsert, true
		}
		if equalsCaseInsensitive(s, "LOOKUP") {
			return TokenKindLookup, true
		}
		if equalsCaseInsensitive(s, "OFFSET") {
			return TokenKindOffset, true
		}
		if equalsCaseInsensitive(s, "PARAMS") {
			return TokenKindParams, true
		}
		if equalsCaseInsensitive(s, "PHRASE") {
			return TokenKindPhrase, true
		}
		if equalsCaseInsensitive(s, "RERANK") {
			return TokenKindRerank, true
		}
		if equalsCaseInsensitive(s, "SAMPLE") {
			return TokenKindSample, true
		}
		if equalsCaseInsensitive(s, "SCALAR") {
			return TokenKindScalar, true
		}
		if equalsCaseInsensitive(s, "SCROLL") {
			return TokenKindScroll, true
		}
		if equalsCaseInsensitive(s, "SELECT") {
			return TokenKindSelect, true
		}
		if equalsCaseInsensitive(s, "SPARSE") {
			return TokenKindSparse, true
		}
		if equalsCaseInsensitive(s, "TARGET") {
			return TokenKindTarget, true
		}
		if equalsCaseInsensitive(s, "UPDATE") {
			return TokenKindUpdate, true
		}
		if equalsCaseInsensitive(s, "VALUES") {
			return TokenKindValues, true
		}
		if equalsCaseInsensitive(s, "VECTOR") {
			return TokenKindVector, true
		}
	case 7:
		if equalsCaseInsensitive(s, "BETWEEN") {
			return TokenKindBetween, true
		}
		if equalsCaseInsensitive(s, "CONTEXT") {
			return TokenKindContext, true
		}
		if equalsCaseInsensitive(s, "NEAREST") {
			return TokenKindNearest, true
		}
		if equalsCaseInsensitive(s, "PAYLOAD") {
			return TokenKindPayload, true
		}
		if equalsCaseInsensitive(s, "PRODUCT") {
			return TokenKindProduct, true
		}
		if equalsCaseInsensitive(s, "VECTORS") {
			return TokenKindVectors, true
		}
	case 8:
		if equalsCaseInsensitive(s, "DEFAULTS") {
			return TokenKindDefaults, true
		}
		if equalsCaseInsensitive(s, "DISABLED") {
			return TokenKindDisabled, true
		}
		if equalsCaseInsensitive(s, "DISCOVER") {
			return TokenKindDiscover, true
		}
		if equalsCaseInsensitive(s, "FEEDBACK") {
			return TokenKindFeedback, true
		}
		if equalsCaseInsensitive(s, "GEO_BBOX") {
			return TokenKindGeoBbox, true
		}
		if equalsCaseInsensitive(s, "PREFETCH") {
			return TokenKindPrefetch, true
		}
		if equalsCaseInsensitive(s, "QUANTILE") {
			return TokenKindQuantile, true
		}
		if equalsCaseInsensitive(s, "QUANTIZE") {
			return TokenKindQuantize, true
		}
		if equalsCaseInsensitive(s, "STRATEGY") {
			return TokenKindStrategy, true
		}
	case 9:
		if equalsCaseInsensitive(s, "MANHATTAN") {
			return TokenKindManhattan, true
		}
		if equalsCaseInsensitive(s, "RECOMMEND") {
			return TokenKindRecommend, true
		}
		if equalsCaseInsensitive(s, "RELEVANCE") {
			return TokenKindRelevance, true
		}
		if equalsCaseInsensitive(s, "THRESHOLD") {
			return TokenKindThreshold, true
		}
	case 10:
		if equalsCaseInsensitive(s, "COLLECTION") {
			return TokenKindCollection, true
		}
		if equalsCaseInsensitive(s, "GEO_RADIUS") {
			return TokenKindGeoRadius, true
		}
		if equalsCaseInsensitive(s, "GROUP_SIZE") {
			return TokenKindGroupSize, true
		}
		if equalsCaseInsensitive(s, "HAS_VECTOR") {
			return TokenKindHasVector, true
		}
		if equalsCaseInsensitive(s, "OPTIMIZERS") {
			return TokenKindOptimizers, true
		}
	case 11:
		if equalsCaseInsensitive(s, "COLLECTIONS") {
			return TokenKindCollections, true
		}
	case 12:
		if equalsCaseInsensitive(s, "VALUES_COUNT") {
			return TokenKindValuesCount, true
		}
	}
	return 0, false
}

func equalsCaseInsensitive(s, upper string) bool {
	if len(s) != len(upper) {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c >= 'a' && c <= 'z' {
			c -= 32
		}
		if c != upper[i] {
			return false
		}
	}
	return true
}
