package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"sort"
	"strings"
)

func main() {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, "lexer.go", nil, 0)
	if err != nil {
		panic(err)
	}

	var keywords map[string]string

	ast.Inspect(node, func(n ast.Node) bool {
		decl, ok := n.(*ast.GenDecl)
		if !ok || decl.Tok != token.VAR {
			return true
		}
		for _, spec := range decl.Specs {
			vspec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for _, name := range vspec.Names {
				if name.Name == "keywords" {
					if comp, ok := vspec.Values[0].(*ast.CompositeLit); ok {
						keywords = make(map[string]string)
						for _, elt := range comp.Elts {
							kv := elt.(*ast.KeyValueExpr)
							k := kv.Key.(*ast.BasicLit).Value
							v := kv.Value.(*ast.Ident).Name
							keywords[strings.Trim(k, `"`)] = v
						}
					}
				}
			}
		}
		return true
	})

	if keywords == nil {
		panic("keywords map not found")
	}

	var keys []string
	for k := range keywords {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var buf bytes.Buffer
	buf.WriteString(`// Code generated by go generate; DO NOT EDIT.

package lexer

func lookupKeywordFast(s string) (TokenKind, bool) {
	if len(s) == 0 {
		return 0, false
	}
	switch len(s) {
`)

	byLen := make(map[int][]string)
	for _, k := range keys {
		byLen[len(k)] = append(byLen[len(k)], k)
	}

	var lengths []int
	for l := range byLen {
		lengths = append(lengths, l)
	}
	sort.Ints(lengths)

	for _, l := range lengths {
		buf.WriteString(fmt.Sprintf("\tcase %d:\n", l))
		buf.WriteString("\t\tswitch s[0] | 0x20 {\n")

		byFirstChar := make(map[byte][]string)
		for _, k := range byLen[l] {
			ch := strings.ToLower(k)[0]
			byFirstChar[ch] = append(byFirstChar[ch], k)
		}

		var chars []int
		for c := range byFirstChar {
			chars = append(chars, int(c))
		}
		sort.Ints(chars)

		for _, c := range chars {
			ch := byte(c)
			buf.WriteString(fmt.Sprintf("\t\tcase '%c':\n", ch))
			for _, k := range byFirstChar[ch] {
				buf.WriteString(fmt.Sprintf("\t\t\tif hasPrefixCaseInsensitive(s, \"%s\") {\n", k))
				buf.WriteString(fmt.Sprintf("\t\t\t\treturn %s, true\n", keywords[k]))
				buf.WriteString("\t\t\t}\n")
			}
		}
		buf.WriteString("\t\t}\n")
	}

	buf.WriteString(`	}
	return 0, false
}
`)

	err = os.WriteFile("keyword_lookup_fast.go", buf.Bytes(), 0644)
	if err != nil {
		panic(err)
	}
	fmt.Println("Generated keyword_lookup_fast.go")
}
